### PR TITLE
Making password change erroring more friendly

### PR DESCRIPTION
**Pull request by Jorropo**
If you leave the form but the 2 password is different a big red box appears to warn you (no need to click on the button).

The submit button is desactivated if the 2 password isn't the same.

### CODE REVIEW

**Comment by Chocobozzz** [comment]
I don't really like that an error message is displayed while I'm currently filling the form

**Comment by Jorropo** [comment]
@Chocobozzz fixed, now the error message is printed only when you leave the form.
One bug is staying but this is angular fault not mine (cause this is working for the button).
If you taped a wrong password and leave, the message appears but after you correct it, normally you don't have to leave the forms for make the message deasapear but you have to leave it.

**Comment by Chocobozzz** [comment]
What's the difference with the previous behaviour? Before this PR, we display the error when the user clicks on the button, and now it's when he leaves the confirmation input field (in theory to click on the button). So I don't think this is really useful

**Comment by Jorropo** [comment]
Beffore it were needed to click on the send button, now you can't click button,
I know that not the PR of the year, it just saves one click. But I do it cause I try to change my password, I type to fast on my keyboard but don't see it and push the button, then when I see the message I was thinking : "why it let me click on the button if it knows that will fail ?" so I change that.

**Comment by Chocobozzz** [comment]
Ok i understand! :+1:

**Pull request merged**
