### PR TITLE
[WIP] Add sortable for videoQuotaUsed in user-list component.

### PR DESCRIPTION
**Pull request by darnuria**

### CODE REVIEW

**Comment by darnuria** [comment]
With @rigelk I found the component to change in the client, but it need changes in the server side:

```[1] [localhost:9000] 2019-07-23 01:28:20.753 warn: Incorrect request parameters {
[1]   "path": "/api/v1/users/?start=0&count=10&sort=videoQuotaUsed",
[1]   "err": {
[1]     "sort": {
[1]       "location": "query",
[1]       "param": "sort",
[1]       "value": "videoQuotaUsed",
[1]       "msg": "Should have correct sortable column"
[1]     }
[1]   }
[1] }
```
It's because videoQuotaUsed is a function not a SQL column.

(mostly notes to myself and @rigelk to continue the PR in the week)

There is some bits of solution in `server/models/account/user.ts` and  `server/models/utils.ts`.

**Comment by Chocobozzz** [comment]
See https://github.com/Chocobozzz/PeerTube/issues/1741#issuecomment-514079151

**Comment by darnuria** [comment]
Hi, @Chocobozzz thanks for your advise ! I reported it from #1741 here:

> @darnuria yes, but you'll also have to update the backend (add videoQuotaUsed to the array)

With @rigelk I tried this option alas videoQuotaUsed,  is not a SQL column it's a SubQuery defined here: 

https://github.com/Chocobozzz/PeerTube//blob/50b4dcce56275e57fc15ade7529f5c501cad150d/server/models/account/user.ts#L619

**Comment by Chocobozzz** [comment]
Oh right. I'll update the server myself, because it's a little more complex than I thought

**Comment by Chocobozzz** [comment]
Actually, it was not that hard :) https://github.com/Chocobozzz/PeerTube/commit/aa3796bda5a6776e0d21048239f25d385a8e7545 

Thanks @darnuria

**Comment by darnuria** [comment]
I was busy this week, no problem for completing my work. :) :+1: 

I would have had the time this weekend to work on it!

**Pull request merged**
