### PR TITLE
Fix/connection with email

### PR DESCRIPTION
**Pull request by NassimBounouas**
This pull concerns #1916 and make login case sensitive for email / case insensitive for username.

### CODE REVIEW

**Comment by Chocobozzz** [comment]
Could you add a unit test? 

Here: https://github.com/Chocobozzz/PeerTube/blob/develop/server/tests/api/users/users.ts#L114
See the documentation: https://github.com/Chocobozzz/PeerTube/blob/develop/.github/CONTRIBUTING.md#unit-tests

**Comment by NassimBounouas** [comment]
Hi @Chocobozzz,

Thank you for the pointer. I thought about adding  a unit test but I didn't know where to do it. I'll work on this.

**Comment by NassimBounouas** [comment]
@Chocobozzz I tried to run the test suite following the doc before adding mine and I encountered this problem :

```
  Test a client controllers
    1) "before all" hook for "Should have valid Open Graph tags on the watch page with video id"
    2) "after all" hook for "Should have valid index html updated tags (title, description...)"


  0 passing (2m)
  2 failing

  1) Test a client controllers
       "before all" hook for "Should have valid Open Graph tags on the watch page with video id":
     Error: Timeout of 120000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (/home/user/dev/PeerTube/server/tests/index.ts)
```

Do you any idea of the root cause ? Thank you !

**Comment by Chocobozzz** [comment]
@NassimBounouas Just run the test you updated, because running all the test suite is quite long. Travis can do this for you.

To run the client controllers test, you need to `npm run build -- --light` (to build the english client). Could you update the contributing guide and replace `npm run build` with `npm run build -- --light`?

**Comment by NassimBounouas** [comment]
@Chocobozzz I'll update the contrib guide at the same time I will push a test. Thank you for the advice. 

While I'm trying to just run one controller test I'm encountering a timeout. What can be the reason ?

`
$ npm run mocha -- --exit --require ts-node/register/type-check --bail server/tests/api/index.ts

> peertube@1.3.1 mocha /home/user/dev/PeerTube
> mocha "--exit" "--require" "ts-node/register/type-check" "--bail" "server/tests/api/index.ts"



  Test activitypub
    1) "before all" hook for "Should return the account object"


  0 passing (30s)
  1 failing

  1) Test activitypub
       "before all" hook for "Should return the account object":
     Error: Timeout of 30000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (/home/user/dev/PeerTube/server/tests/api/index.ts)
`

**Comment by Chocobozzz** [comment]
Try to run `npm run clean:server:test && NODE_APP_INSTANCE=1 NODE_ENV=test npm start` to see what's wrong

**Comment by NassimBounouas** [comment]
I'll recreate a clean environment later in the day. I'm using a postgresql db and a redis db that are both run into a docker container so the cleaning script can't be directly used.

**Comment by NassimBounouas** [comment]
Hi @Chocobozzz,

I finally successed to run the test suite with databases directly installed on my computer and I have few questions. In the documentation [there](https://docs.joinpeertube.org/#/contribute-getting-started?id=unit-tests) there is those two commands :

```
$ sudo -u postgres createuser you_username --createdb --superuser
$ createdb -O peertube peertube_test{1,2,3,4,5,6}
```

1) Does the part  `-O peertube` on the second command should not be the same as `you_username` ?
2) Does the second command needs a specific version of postgresql because it returns me the following error : 

```
$ sudo -u postgres createdb -O peertube peertube_test{1,2,3,4,5,6}
createdb: too many command-line arguments (first is "peertube_test3")
Try "createdb --help" for more information.
```
I created 6 databases prefixed with `peertube_test` and it seems to work.

According your answers I will update the contribution guide.

Thank you

**Comment by Chocobozzz** [comment]
> Does the part -O peertube on the second command should not be the same as you_username ?

No it should be `peertube`, because it's the postgresql user we declared in the default configuration file that test instances use. `sudo -u postgres createuser you_username --createdb --superuser` is used by PeerTube test scripts (`npm run clean:server:test`) to create and drop databases without using the `postgres` user. 

> Does the second command needs a specific version of postgresql because it returns me the following error 

I think the documentation is wrong. We could replace this with `npm run clean:server:test` that will create these databases.

**Comment by NassimBounouas** [comment]
Hi @Chocobozzz !

After some experimentation I think that I understood the peertube unit tests structure and add a test about the username case insensitivity during the login. Can you tell me if my test fits  to your expectation ? 

Just to be sure about what I understood : the credentials used in the test suite are set [there](https://github.com/Chocobozzz/PeerTube/blob/develop/shared/extra-utils/server/servers.ts#L211) from an extract (using regex) of the test server standard output [there](https://github.com/Chocobozzz/PeerTube/blob/develop/server/initializers/installer.ts#L150), am I right ?

I also updated the documentation for the build part and the test databases clean process.

Subsidiary question : I saw few unit tests that are in pending state, is there any issue related to this in order to contribute ?

Thank you

**Comment by Chocobozzz** [comment]
> Just to be sure about what I understood : the credentials used in the test suite are set there from an extract (using regex) of the test server standard output there, am I right ?

Yep!

> Subsidiary question : I saw few unit tests that are in pending state, is there any issue related to this in order to contribute ?

I don't remember all of them, but I think you can try to implement some of them :)

**Pull request merged**
