### PR TITLE
Remove modal writing-on-blackboard simulator

### PR DESCRIPTION
**Pull request by scanlime**
These are admins, not children, seriously. I don't want this in my copy of PeerTube, and I figured other admins must be super annoyed by this too. I'm going to start patching this out of my copy, and possibly running a fork on my server.

### CODE REVIEW

**Comment by rigelk** [comment]
LGTM, but you might want to remove "These are admins, not children, seriously." from the commit message description.

**Comment by scanlime** [comment]
Sure, amended the commit message. It was unfair to children anyway, I don't remember this kind of thing helping when I was younger either :)

**Comment by rigelk** [comment]
Now that I think of it, that was the only use of the `ConfirmService` in this file - could you remove the import and declaration in the rest of the file?

**Comment by rigelk** [comment]
Thanks @scanlime :)

**Comment by scanlime** [comment]
Thanks for the merge!

**Pull request merged**
