### PR TITLE
Patch 1

### PR DESCRIPTION
**Pull request by hspeijer**
## Description

Small documentation change to ensure correct version of ffmpeg on ubuntu 18

## Has this been tested?

- [ ] 👍 yes, I added tests to the test suite
- [ ] 👍 yes, light tests as follows are enough
- [ ] 💭 no, because this PR is a draft and still needs work
- [ ] 🙅 no, because they aren't needed
- [ ] 🙋 no, because I need help

### CODE REVIEW

**Comment by rigelk** [comment]
hi @hspeijer,

I don't think we should be reliant on snap, unless this is the way Ubuntu advises to install a recent enough ffmpeg version.

**Comment by Chocobozzz** [comment]
@rigelk AFAIK ubuntu 18 only has ffmpeg 3.x, so not compatible with our HLS option. Snap seems the recommended way to install packages on ubuntu no?

**Comment by tcitworld** [comment]
Ubuntu 18.04 is not the latest LTS though.

**Comment by hspeijer** [comment]
I am not sure if ubuntu 20 does come with a newer version of ffmpeg. In any case I managed to make it work using this page (https://launchpad.net/~savoury1/+archive/ubuntu/ffmpeg4) which might be worthy to be included in the documentation as a side note for ubuntu 18 which is still being used a lot.

**Pull request closed without merging**
