### PR TITLE
Set keyframe interval

### PR DESCRIPTION
**Pull request by Nutomic**
Turns out that I was wrong in #1147, the `-g` paramater for keyframes is only deprecated for H265, but works fine for H264. 

Unfortunately fluent-ffmpeg doesn't return the keyframe interval, and doesn't have an option to set parameters. So I think the only way to get the keyframe interval of an existing video (for tests and `optimize-old-videos.ts`) is by running the command on a shell. But I'm not sure how that works, or if it's a good idea. This is the command to list all keyframe times ([source](https://stackoverflow.com/a/18088156)):
```
ffprobe -loglevel error -skip_frame nokey -select_streams v:0 -show_entries frame=pkt_pts_time -of csv=print_section=0
```
This PR depends on #1135.

### CODE REVIEW

**Comment by Nutomic** [comment]
Here's a diff for easier reading:
```
diff --git a/server/helpers/ffmpeg-utils.ts b/server/helpers/ffmpeg-utils.ts
index 8e447117..26f99bc8 100644
--- a/server/helpers/ffmpeg-utils.ts
+++ b/server/helpers/ffmpeg-utils.ts
@@ -114,6 +114,10 @@ type TranscodeOptions = {
   isPortraitMode?: boolean
 }

+/**
+ * Transcodes a video to H264. Don't use it for other output formats, as
+ * parameters might be different.
+ */
 function transcode (options: TranscodeOptions) {
   return new Promise<void>(async (res, rej) => {
     let command = ffmpeg(options.inputPath, { niceness: FFMPEG_NICE.TRANSCODING })
@@ -154,6 +158,11 @@ function transcode (options: TranscodeOptions) {
     const targetBitrate = getTargetBitrate(options.resolution, fps, VIDEO_TRANSCODING_FPS)
     command.outputOptions([`-b:v ${ targetBitrate }`, `-maxrate ${ targetBitrate }`, `-bufsize ${ targetBitrate * 2 }`])

+    // Keyframe interval of 2 seconds for faster seeking and resolution switching.
+    // https://streaminglearningcenter.com/blogs/whats-the-right-keyframe-interval.html
+    // https://superuser.com/a/908325
+    command.outputOption(`-g ${ fps * 2 }`)
+
     command
       .on('error', (err, stdout, stderr) => {
         logger.error('Error in transcoding job.', { stdout, stderr })
```

**Comment by rigelk** [comment]
@Nutomic last time I refactored `ffmpeg-utils.ts`, I added presets which can be seen at the bottom of the file. It is meant to decouple the encoding profile and its options (which as you point out can be very specific) from the transcoding function.

So if you have a h264-specific encoding option, why not put it in `standard`, line 276? It might not be easy to pass the `fps`, though :thinking:

**Comment by Nutomic** [comment]
Ah I wasn't sure what the preset was about exactly. How about renaming it to h264Profile or something like that? It would also make sense to move the code for video bitrate there.And then we could just pass fps and resolution as parameters?

**Comment by rigelk** [comment]
@Nutomic sure! Right now only the standard preset is used, but the other two presets I added along were meant as the base for a later choice of a lighter transcoding profile by the admin (using veryfast for instance).

But it's just an idea of a later refactoring. Your PR is fine as is.

**Comment by Nutomic** [comment]
I can certainly take care of that to save you some work. I'm just not sure what's the best way to solve it, because the presets function can't take any extra parameters. So either:
- change the function to `standard(ffmpeg, fps, resolution)`, and call it as a normal function from `transcode()`
- leave `standard()` as a preset function, and calculate fps/resolution again

**Comment by rigelk** [comment]
@Nutomic could you rebase your PR now that the `ffmpeg-utils` have changed in develop?

**Pull request closed without merging**
