### PR TITLE
add fields.users.username.max to config

### PR DESCRIPTION
**Pull request by FlatEarthTruther**
issue #1188 allow username to be longer than 20 chars, giving option to administrators to control this from config

### CODE REVIEW

**Comment by FlatEarthTruther** [comment]
The reason for the deep nesting is to allow for further to add options later in the future, when more fields and constraints are added in later versions.

I left 20 as the default as before, but we should ideal make the default to be 32 chars for usernames.
```
fields:
  users:
    username:
      max: 20
```

**Comment by Chocobozzz** [comment]
Like @Jorropo said :+1:

**Comment by FlatEarthTruther** [comment]
Maybe in the database set the limit to 128 or 64 and make that a hard limit, whereas the admin can set a soft-limit on the username max length.

**Comment by FlatEarthTruther** [comment]
if 32 could be the new limit it would be ideal, since most usernames would be within that limit, I have downloaded many account videos and some accounts have long username, but for the most part they fit within the 32 char limit, so for it to be limited to 20 chars affects a lot of accounts

**Pull request closed without merging**
