### PR TITLE
Adding frontend peertubeHelpers.getBaseRouterRoute.

### PR DESCRIPTION
**Pull request by JohnXLivingston**
## Description

As discussed in private with @Chocobozzz , here is the frontend version for peertubeHelpers.getBaseRouterRoute.

For the documentation part, I did not know which peertube version to mention. 3.3.0 ? 4.0.0 ? other?

## Has this been tested?

- [ ] 👍 yes, I added tests to the test suite
- [ ] 👍 yes, light tests as follows are enough
- [ ] 💭 no, because this PR is a draft and still needs work
- [x] 🙅 no, because they aren't needed
- [ ] 🙋 no, because I need help

There is no test file for this front-end code.
I tested with one of my plugin (see commit https://github.com/JohnXLivingston/peertube-plugin-livechat/commit/22f392d8384e164cee1520793ae9ef3278b3dcfe )

### CODE REVIEW

**Comment by Chocobozzz** [comment]
3.3 :+1: 

But I think there is something wrong in the doc toc command, `- [Plugins & Themes](#plugins--themes)` should not be included

**Comment by JohnXLivingston** [comment]
> But I think there is something wrong in the doc toc command, `- [Plugins & Themes](#plugins--themes)` should not be included

I have no idea how doc toc works. I only added lines outside the doctoc block, and run a `npm run build`. And then I got this diff.

**Comment by JohnXLivingston** [comment]
I fixed the doctoc.

I don't understand how it works. When I edit with Visual Studio Code, it auto-generates wrongly this part. I don't know how to disable, nor to configure. There is nothing like «doctoc» in the settings or plugins.

**Comment by JohnXLivingston** [comment]
Ok, I found the settings in Visual Studio Code: Markdown > Extension > Toc: update on save.

**Comment by Chocobozzz** [comment]
Thanks @JohnXLivingston

**Pull request merged**
