### PR TITLE
Add channel name to create-user admin form

### PR DESCRIPTION
**Pull request by kimsible**
Required fix : https://github.com/Chocobozzz/PeerTube/issues/2970

image

### CODE REVIEW

**Comment by Chocobozzz** [comment]
Is it still a WIP?

**Comment by kimsible** [comment]
> Is it still a WIP?

Yes, didn't have time to commit my local changes with the fix.

**Comment by kimsible** [comment]
TODO: `channelName` must be added to `createUser` api doc as an optionnal parameter.

- On client side in the admin panel, `channelName` is required to avoid **Main *username* channel** `displayName` and unwanted unique channel name, this way we follow the signup form which forces the user to give a channel name ;
- **Server side, `channelName` stays optionnal to not break the api**.

**Comment by kimsible** [comment]
Tests has been fixed.

**Comment by Chocobozzz** [comment]
We don't want to autofill the channel name field depending on the user username like we do in the signup form?

**Comment by kimsible** [comment]
> We don't want to autofill the channel name field depending on the user username like we do in the signup form?

You mean adding Display name fields ?

Otherwise, the goal is also to avoid the generic names "kimsible_channel" and "Main kimsible channel", I don't think automatic fill for we don't want anymore is the right thing to do.

In any case the signup form asks username and channel name (with display names) on separate steps.

Display names may be edited by the user after account created.

**Pull request merged**
