### PR TITLE
Add an option to sign federated fetches for mastodon compatibility

### PR DESCRIPTION
**Pull request by irafire**
## Description

Add a minimal set of changes to have remote comments, follows, and likes working with a mastodon instance with AUTHORIZED_FETCH enabled, guarded by a config flag.

Considering this a draft due to missing test coverage and only light manual testing, but uploading in case somebody is in a hurry to try to apply this to their setup. It is also possible that some federated functionality I have not considered is still failing.

## Related issues

https://github.com/Chocobozzz/PeerTube/issues/4226

## Has this been tested?

- [ ] 👍 yes, I added tests to the test suite
- [x] partially, by the existing test suite and a manual deployment 
- [ ] 💭 no, because this PR is a draft and still needs work
- [ ] 🙅 no, because this PR does not update server code
- [x] 🙋 no, because I need help 

The existing suite passed for me with flag enabled in test config (and caught an initial mistake, so some of the affected paths are exercised). I've also deployed it in a docker container built on top of v5.2.0 and it seems to pass initial manual testing i.e. comments, likes, and follow requests work with a secure fetch mastodon instance. I am not sure what tests to update/create (also I don't have Node experience), so the functionality is put behind a config flag. Marking this as need help in case contributing required testing coverage turns out to be easy for me to follow up on.

### CODE REVIEW

**Comment by dannekrose** [comment]
Thank you for the PR!  I really hope that it can get integrated since Secure/Authorized Fetch is becoming the standard more and more.

**Comment by Chocobozzz** [comment]
Do you think it's fine that we display publicly information we got via a signed fetch?

**Comment by dannekrose** [comment]
> Do you think it's fine that we display publicly information we got via a signed fetch?

I would say for anonymous users, no.  But for logged in users yes because those users would share the same domain name/instance as the content that the remote account has allowed to retrieve the content.  That content also would not be federated out to following instances and only stay local to the PeerTube instance (how it works on the Microblogging platforms).

That adds a lot more complexity for sure, but I think matches the intent of Signed Fetch's idea of security and privacy. 


In addition to this, I understand the model is a bit different being a video/media sharing platform, but adding the ability to also require signed fetch for PeerTube content as an option for admins would be very useful.  It does potentially make the content less discoverable since it requires authentication to view, but for some admins, that allows them to better control their content, especially content that is NSFW or requires much stricter access controls without necessarily needing to have all viewers of the content create accounts on that same instance to view.  (i.e. restrict to Signed Fetch, and then require approval to follow accounts, or channels on the instance).

**Comment by Chocobozzz** [comment]
Thanks! I refactored a little bit this PR.

I think it's okay to display publicly information we fetched using signed fetch if they're public. And PeerTube respects the remote object privacy anyway.

I decided to enable this feature by default, as I see many 403 from Mastodon. We'll see if it leads to performance issues.

**Pull request merged**
