### PR TITLE
feat: add support for sub routes under /my-account

### LINKED ISSUE #6217: Custom client routes under My account
### Describe the problem to be solved

We'd like to add custom client routes under /my-account via the plugins API. We'd also like to embed the sub menu and add menu items.

### Describe the solution you would like

```
  registerClientRoute({
    route: '/sub-route',
    parentRoute: '/my-account',
    menuItem: {
      label: 'Sub route',
    },
    onMount: ({ rootEl }) => {
      rootEl.innerText = 'Hi, this is a sub route with menu included.';
    }
  })
```

image

### PR DESCRIPTION
**Pull request by kontrollanten**
## Description
Extending plugin API for custom routes:

* Support for custom routes under /my-account with My account menu shown on the top.
* Support for adding custom menu items to the My account menu.
* Support for adding page titles for all type of custom routes.

```
  registerClientRoute({
    route: '/sub-route',
    parentRoute: '/my-account',
    menuItem: {
      label: 'Sub route',
    },
    title: 'Custom sub route',
    onMount: ({ rootEl }) => {
      rootEl.innerText = 'Hi, this is a sub route with menu included.';
    }
  })
```

Example plugin at https://framagit.org/kontrollanten/test-sub-routes

### Alternative solutions
Initially the plan as was to add ` filter:my-account-menu.links.create.result` API to add links in the menu, but then this proposed solution felt more natural and intuitive.

## Related issues
closes #6217

## Has this been tested?

- [ ] 👍 yes, I added tests to the test suite
- [ ] 💭 no, because this PR is a draft and still needs work
- [ ] 🙅 no, because this PR does not update server code
- [x] 🙋 no, because I need help 

I couldn't find any paved up way to add tests for this.

## Screenshots
image
image

### CODE REVIEW

**Comment by kontrollanten** [comment]
@Chocobozzz Any comments on the design here? If everything looks ok I can fix the conflicts to make it available for 6.1.

**Comment by Chocobozzz** [comment]
Hi,

Sorry for the late review, and the conflicts. I think we're good with the design. Can you try to also refactor the PR to use standalone components?

**Comment by kontrollanten** [comment]
Sure. Just to verify that we're talking about the same, you mean [Angular standalone components](https://angular.io/guide/standalone-components)?

**Comment by kontrollanten** [comment]
Now the conflicts are solved and it's using standalone components.

**Comment by kontrollanten** [comment]
I added a commit that calls the plugins `onMount` upon each URL change. Otherwise routes won't update when switching between /my-account/p/plugin-1 and /my-account/p/plugin-2.

**Comment by Chocobozzz** [comment]
Thanks! Can you add the new feature in the documentation? https://github.com/Chocobozzz/PeerTube/blob/develop/support/doc/plugins/guide.md#create-client-page

**Comment by Chocobozzz** [comment]
Thanks!

**Comment by JohnXLivingston** [comment]
Hi,

Is there a way to test if the feature is available? (so we can only add such routes if the Peertube current version supports this feature).

**Comment by Chocobozzz** [comment]
> Is there a way to test if the feature is available?

Not specifically, but you can use `getServerConfig()` plugin helper and check peertube >= 6.1.0

**Comment by JohnXLivingston** [comment]
> Not specifically, but you can use `getServerConfig()` plugin helper and check peertube >= 6.1.0

Of course. Just this goes against the usual good practices (where we should test if a method is available, rather than testing the Peertube version).
Will do so if needed, thanks :)

**Pull request merged**
