### PR TITLE
adjust registration form width on mobile

### PR DESCRIPTION
**Pull request by test2a**
fixed box size was forcing more than 100% screen on mobile devices. this should help. i could be wrong though

### CODE REVIEW

**Comment by test2a** [comment]
Screen Shot 2020-11-07 at 14 52 06

**Comment by test2a** [comment]
@rigelk can you please check if this actually works or  am i just imagining things here?

**Comment by rigelk** [comment]
@test2a it works at that screen size, but then it changes it for _all display sizes too_…

**Comment by test2a** [comment]
@rigelk in that case i think i will switch this over to draft because it would need some time

**Comment by test2a** [comment]
@rigelk would this work now?

**Comment by rigelk** [comment]
@test2a no. specifically, you need [media queries](https://developer.mozilla.org/en-US/docs/Web/CSS/Media_Queries/Using_media_queries) as is done [here](https://github.com/Chocobozzz/PeerTube//blob/583eb04b541175035d6d452ca626a96ebf2b7437/client/src/app/app.component.scss#L73).

**Comment by rigelk** [comment]
@test2a please open a new PR once you are done with your implementation

**Pull request closed without merging**
