### PR TITLE
Basic video redundancy implementation

### PR DESCRIPTION
**Pull request by Chocobozzz**
For now there is only 1 strategy: `most-views` that caches videos with the most views.

### CODE REVIEW

**Comment by Nutomic** [comment]
Are those redundant videos stored in the normal video folder? Would be useful if we could put the cache on a faster disk.

**Comment by Chocobozzz** [comment]
> Are those redundant videos stored in the normal video folder? Would be useful if we could put the cache on a faster disk.

The normal video folder should be in a fast disk.

> Edit: It would also be nice if local videos could be mirrored into the cache. That way we could use slow, cheap storage for all videos, and fast storage for popular videos.

Related to https://github.com/Chocobozzz/PeerTube/issues/765

**Comment by Nutomic** [comment]
Well fast disks are expensive, and the majority of videos are barely ever watched. So it makes sense to store the few popular videos on a fast disk, and the rest on a slow disk (still fast enough for streaming). If all videos have to be stored on fast disks, that would make Peertube extremely expensive to host.

**Comment by Chocobozzz** [comment]
When I talk about fast disk, I mean hard disk (and not a cold storage for example).

If you want a dedicated directory for old/unused videos (so you can put it in a slow and cheap storage), please create an issue.

**Comment by Nutomic** [comment]
Okay done: #1086

**Pull request merged**
