### PR TITLE
authenticate upload requests before they transmit video

### PR DESCRIPTION
**Pull request by rigelk**
## Description

Adds a simple route to check for proper authentification before any traffic reaches the backend. The route is used internally and prevents requests to DDoS a PeerTube server with a large client body size.

## Has this been tested?

- [x] 💭 no, because this PR is a draft and still needs work

Ideally the app should be tested on a live instance running with the new route.

### CODE REVIEW

**Comment by Chocobozzz** [comment]
What's the use case? To prevent upload failure with the web client due to bad auth? Or another thing?

**Comment by rigelk** [comment]
@Chocobozzz to prevent DDoS transferring up to 8Gb before the request is even authenticated.

**Comment by Chocobozzz** [comment]
Okay then `proxy_request_buffering` to `off` could actually fix this issue in a better way?

**Comment by Chocobozzz** [comment]
Closing due to inactivity. Feel free to reopen

**Pull request closed without merging**
