### PR TITLE
Use alpine images with docker-compose

### PR DESCRIPTION
**Pull request by Angristan**
Works the same, but lighter. I think it's a good idea to add them in the `docker-compose.yml` example.

### CODE REVIEW

**Comment by Angristan** [comment]
Maybe we should also put the peertube:alpine image in the docker-compose.yml if you don't see any drawback.

**Comment by rigelk** [comment]
@Angristan that would be fine by me. @bnjbvr ?

**Comment by bnjbvr** [comment]
@Angristan Are you using the Alpine docker image? I've seen you mentioned a few segfaults on Mastodon when using PeerTube, so if you're using Alpine (which uses musl, for which native programs might need recompilation), I'd rather avoid it in the meanwhile and keep on using the Debian image instead.

**Comment by Angristan** [comment]
Yep, let's keep the Debian image for peertube for now 😄

**Comment by bnjbvr** [comment]
@Angristan Just to confirm: was it actually the Peertube alpine image that got the segfaults, or the postgres or redis alpine ones?

**Comment by Angristan** [comment]
Yes: 
d80ea2168cbf4e73

No issue with peertube:stretch with alpine postgres/redis

**Comment by rigelk** [comment]
Then I guess we can merge this PR as it stands.

**Pull request merged**
