### PR TITLE
Add doc for config VPS

### PR DESCRIPTION
**Pull request by auberanger**
Hello, I'm a CS french student working on PeerTube with two friends (@am97 and @clementbrizard ) as a scholar project.

We've been trying to run PeerTube on a VPS for a while and finally managed to do it. We now have a working developping environnement, with the live-reload feature.

Here is an adding proposition for the documentation.

### CODE REVIEW

**Comment by rigelk** [comment]
IMHO the subject is broad enough to have its place in https://framagit.org/framasoft/peertube/documentation rather than within the core repository.

**Comment by auberanger** [comment]
Ok, thanks, but I'm not sure to understand where exacly do you mean this subject would have it's place in [docs.joinpeertube.org](docs.joinpeertube.org). Cause [there](https://framagit.org/framasoft/peertube/documentation/blob/master/lang/en/org/contributing.md), all the links refer to this github repository.

**Comment by auberanger** [comment]
Would it be on this page : [Installation | PeerTube](https://docs.joinpeertube.org/lang/en/docs/install.html) ? If yes, near "Before you start using PeerTube, you'll first need to install it on your server." ?

**Comment by rigelk** [comment]
I wouldn't clutter the Install page (which is a _tutorial_ aimed at _production installs_), as your paragraph is aimed at developers.

The documentation is not yet fully structured, so I'm not saying there is a specific place to put it right now. [docs.joinpeertube.org](http://docs.joinpeertube.org/) is certainly lacking a section dedicated to hacking on PeerTube. Perhaps until then, we can merge this.

**Comment by auberanger** [comment]
Thanks for the answer. To merge this seems a good compromise for now. We'll still be able to enhance the structure in proper time.

**Comment by rigelk** [comment]
@auberanger I have added it to https://docs.joinpeertube.org/lang/en/devdocs/vps.html

**Pull request merged**
