### PR TITLE
 Issue #168: youtube-like marking of comments

### PR DESCRIPTION
**Pull request by jonathanraes**
Uses GET parameters to mark comments similar to youtube, allowing to send a comment link to someone else.
I agree with Aluriak that the « x min ago » text is not a logical place to provide the link, even though this is the case in youtube. (#168)
Right now I included a link next to the `Delete` and `Reply` links, but i'm open to changing that.

### CODE REVIEW

**Comment by Chocobozzz** [comment]
Awaiting a better solution I prefer to put the link in the " x min ago " text :)

**Comment by tcitworld** [comment]
Using a `GET` parameter isn't really sexy. Couln't we have a dedicated route ?

**Comment by Chocobozzz** [comment]
An anchor tag would be useful, but we can't for now: https://github.com/angular/angular/issues/6595

Maybe we could just use [params](https://angular.io/api/router/ActivatedRouteSnapshot#params) for now (like in the videos list).

**Comment by jonathanraes** [comment]
I'll look into using a route and params

**Comment by jonathanraes** [comment]
How about this?

**Comment by Chocobozzz** [comment]
Nice! Thanks @jonathanraes!

**Pull request merged**
