### PR TITLE
Update year to 2019

### PR DESCRIPTION
**Pull request by C0derLint**
Was reading through the README when I noticed the year on it was still 2018. What else could I do but open a PR? ;)

### CODE REVIEW

**Comment by Nutomic** [comment]
I think this should be something like 2018-2019. But I dont know much about copyright.

**Comment by Serkan-devel** [comment]
I think peertube has existed even earlier

**Comment by C0derLint** [comment]
@Nutomic The first commit to the project is in 2015 :D

**Comment by Chocobozzz** [comment]
From https://www.gnu.org/licenses/gpl-howto.en.html (**The copyright notice** section) I think we should write 2015-2019

**Comment by Chocobozzz** [comment]
Thanks @C0derLint

**Pull request merged**
