### PR TITLE
Instance homepage support

### PR DESCRIPTION
**Pull request by Chocobozzz**
Add ability for admins to create a custom public homepage in admin config using markdown/html.

I've put some example of dynamic html tags in `CustomMarkupService` (`<peertube-video-embed>`, `<peertube-playlist-miniature>`...) to test Angular component injection. We'll add a proper support for these components + add other components in the future, but in another PR.

### CODE REVIEW

**Comment by Chocobozzz** [comment]
Not ready yet, miss channel and rows of videos that we'll implement later.

**Comment by kimsible** [comment]
Hi @Chocobozzz, I've just tested this new feature, did you plan to implement `` markdown support or directly in css with `background-image` ?

**Comment by Chocobozzz** [comment]
There was bug in the markdown image support that should be fixed by https://github.com/Chocobozzz/PeerTube/commit/0d25c5941466d824e0840b0381e368736f813d51

**Comment by EkkiBrue** [comment]
Is it possible to define this homepage as the first landingpage of peetube somewhere in the administration panel ? Can´t find this setting anywhere and my site always forces me to the "pupular" site.

And then I want to say THANK YOU Chcobuzz for all what you have done to the community support us with such a masterpiece of software!

**Comment by Chocobozzz** [comment]
Thanks :)

Yes, check the blog post: https://joinpeertube.org/news#release-3.3 

> In order to allow as many people as possible to see your homepage, make sure you set it as the default page. To do this, go to the Administration menu, Configuration section, Basic tab and select "Home" in Landing page field.

**Pull request merged**
