### PR TITLE
Add pixel size to tooltip and gif support with FFmpeg for avatar upload

### PR DESCRIPTION
**Pull request by kimsible**
## Description

- Add max resolution 192x192 (after resize) in tooltip avatar upload
- Add gif support for avatar with **FFmpeg process**

## Related issues

Gif support only : https://github.com/Chocobozzz/PeerTube/issues/3299

## Has this been tested?

~~- [ ] 👍 yes, I added tests to the test suite~~ Didn't found any unit test for Image processing
- [x] 👍 yes, light tests as follows are enough

I just live tested, does it need unit test @Chocobozzz  ?

## Screenshots

Peek 19-11-2020 02-13

### CODE REVIEW

**Comment by Chocobozzz** [comment]
> Add gif support for avatar as a copy, Jimp does not support gif resize

I'm sorry but we can't just copy unknown files from users, without resize or compression

**Comment by kimsible** [comment]
> > Add gif support for avatar as a copy, Jimp does not support gif resize
> 
> I'm sorry but we can't just copy unknown files from users, without resize or compression

@Chocobozzz I didn't make it to compress and resize gif with Jimp, would you help ?

**Comment by rigelk** [comment]
@kimsible you might need a plugin for Jimp to bring it support of gifs, like https://github.com/jtlapp/gifwrap

**Comment by kimsible** [comment]
> @kimsible you might need a plugin for Jimp to bring it support of gifs, like https://github.com/jtlapp/gifwrap

@rigelk thanks, you mean with need a new filter / action server side to handle it ? also how can we filter the extensions list constant ?

**Comment by kimsible** [comment]
@rigelk I'm gonna try to use Jimp to compress only the gif and refuse a gif with a greater size than 192*192px, maybe it will be enough to handle in the PeerTube core ?

**Comment by Chocobozzz** [comment]
ffmpeg might me able to resize a gif

**Comment by kimsible** [comment]
Thanks @Chocobozzz @rigelk  for the tips, it now uses FFmpeg to process GIF :

- Reduce to 15 FPS
- Scale to maximum avatar size

Cons :
- It does not handle GIF transparency but white is the default color of FFmpeg, so transparent GIF will fit to the PeeTube design.

**Comment by Chocobozzz** [comment]
Please next time add unit tests.

**Pull request merged**
