### PR TITLE
Add registration approval

### PR DESCRIPTION
**Pull request by Chocobozzz**
## Description

Add registration approval mode. If enabled, a "registration reason" must be filled by the user.
Moderators then need to accept/reject the registration with a "moderation response". An email is sent to the user to notify him/her the registration request has been rejected/accepted.
If the registration request is accepted, the user and the channel are created.

## Related issues

 * https://github.com/Chocobozzz/PeerTube/issues/2242
 * https://github.com/Chocobozzz/PeerTube/issues/5336

## Screenshots

**Request an account signup form**
screen_2023-01-18-16:11:25

**List registrations requests (moderators/admins)**
screen_2023-01-18-16:11:02

**Accept/Reject a registration request**
screen_2023-01-18-16:11:13

### CODE REVIEW

**Comment by JohnXLivingston** [comment]
Great feature @Chocobozzz !

Could you add a checkbox to not send email when rejecting an account creation?

I remember that some time ago, on a forum where I was moderator, some spammers were creating account just to spam: they use the e-mail of someone else, and fill the information (nickname and so on) with spam content. So, even if we reject the account, a mail was sent to the target...

**Comment by Chocobozzz** [comment]
Nice idea. I'll add a bulk action to remove registration entries + the checkbox in the modal.

**Comment by Chocobozzz** [comment]
Done in https://github.com/Chocobozzz/PeerTube/commit/4115f20084f302f497be9cb12237564679ca54ec & https://github.com/Chocobozzz/PeerTube/commit/cd940f40cb62fa105b14e1ce838e97f316c13c5c

**Comment by JohnXLivingston** [comment]
Thanks!

**Comment by PeterAlfonsLoch** [comment]
Thank you <3

**Pull request merged**
