### PR TITLE
WebTorrent Plugin: Clearify error message

### PR DESCRIPTION
**Pull request by kontrollanten**
## Description
This PR shouldn't change any functionality, but just give a more clear error message when `videoFiles`

## Related issues
#3412 

## Has this been tested?

- [x] 👍 yes, light tests as follows are enough

1) Start the dev server
1) Start a video
1) Verify nothing is broken

### CODE REVIEW

**Comment by kontrollanten** [comment]
Updated description with test instructions.

**Comment by Chocobozzz** [comment]
Hi,

Thanks for the PR but I would rather to not "refactor" the webtorrent plugin since it's in maintenance mode. I think the root cause is that `videoFile` could be `null` [here](https://github.com/Chocobozzz/PeerTube/blob/develop/client/src/assets/player/webtorrent/webtorrent-plugin.ts#L126)

Then, we could also throw [here](https://github.com/Chocobozzz/PeerTube/blob/develop/client/src/assets/player/webtorrent/webtorrent-plugin.ts#L141) is `!!videoFile` is `false`

**Comment by kontrollanten** [comment]
I see. Now I've reverted the refactor commits and changed the check to `!!videoFile`.

**Comment by Chocobozzz** [comment]
Thanks @kontrollanten

**Pull request merged**
