### PR TITLE
adjust registration form width on mobile

### PR DESCRIPTION
**Pull request by test2a**
## Description

updated the desired changes in registration form. now it should be 100% width on reasonable length URLs 
@rigelk please have a look at this. i think i managed to get what you were asking
## Type of change

- [ ] ♻️ Refactor discussed in #
- [ ] ✨ Feature as discussed in #
- [x] 🐛 Bug Fix
- [ ] 👷 Optimization/Maintenance
- [ ] 📝 Documentation Update
- [ ] 🔖 Release
- [ ] 🚩 Other

## Has this been tested?

- [ ] 👍 yes, I added tests to the test suite
- [ ] 👍 yes, light tests as follows are enough
- [ ] 💭 no, because this PR is a draft and still needs work
- [ ] 🙅 no, because they aren't needed
- [x] 🙋 no, because I need help

**Self-test configuration**:
* NodeJS version: 
* Viewport sizes: 
* Browser name/version: 

## Checklist:

- [x] I have read the [CONTRIBUTING](./.github/CONTRIBUTING.md) documentation.
- [x] I didn't make the linter cry
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made changes to the documentation as needed
- [ ] I have made changes to the OpenAPI spec as needed
- [x] To the best of my knowledge, my changes introduce no known security vulnerability
- [x] I have corrected any misspellings in my code/comments

### CODE REVIEW

**Review by rigelk — CHANGES_REQUESTED** [review]
Please use only one query to group width changes in one place.
Please use the `mobile-view` breakpoint instead of manually writing its value each time.

**Comment by rigelk** [comment]
@test2a also, can you test this in a browser please? For instance in Firefox, you can use the RDM: https://developer.mozilla.org/en-US/docs/Tools/Responsive_Design_Mode

**Comment by Chocobozzz** [comment]
Hello,

Is it still a draft?

**Comment by test2a** [comment]
i just updated to mobile-view. can you review this

**Comment by rigelk** [comment]
@test2a this code doesn't work since this is not how variables are used in SASS. You need to use them with a `$` prefixing them.

**Comment by rigelk** [comment]
Rebased and corrected lint. Checking visual consistency ASAP.

**Pull request merged**
