### PR TITLE
Include Web Manifest

### PR DESCRIPTION
**Pull request by lucaspontoexe**
Now we need to fix the icons path, which shouldn't be hard.

### CODE REVIEW

**Comment by rigelk** [comment]
why did you add a "GooglePlayStore" icon?

**Comment by lucaspontoexe** [comment]
It is not necessary. I just forgot to delete.

**Comment by Chocobozzz** [comment]
I think `client/src/assets/images/icons/Thumbs.db` should be deleted too?

I'm sorry but I'm not familiar with manifests, what do you mean with "Now we need to fix the icons path, which shouldn't be hard."?

**Comment by lucaspontoexe** [comment]
> "Now we need to fix the icons path, which shouldn't be hard."

At the time I was writing that, I was kind of guessing where the images were stored.

**Pull request merged**
