### PR TITLE
Add config option to keep original video file (basic first version)

### PR DESCRIPTION
**Pull request by chagai95**
## Description
We added a config option to allow keeping the originally uploaded video instead of it being deleted after the transcoding process.

We added the UUID file name to the `videoSource` table, as suggested [here](https://github.com/Chocobozzz/PeerTube/issues/4731#issuecomment-1027923458).

We found two places in the code that delete the original file, both of which need to be skipped in order to keep the original file. The original file is always kept in the `web-videos` directory, in some cases in the `private` directory therein. This seems to be unrelated to whether the video is publicly published or not. Is there a specific reason for that, which we missed?

Also, are there any other places you think we might need to take into account? Maybe we should somehow make use of the columns `pendingMove`, `pendingTranscode` in the `videoJobInfo` table?

We added a new migration file that adds the two columns: `keptOriginalFile` (boolean), `keptOriginalFileName` (UUID original file name)

Things that we would like to add in the future: 

- UI support for admin
- per video based support where the user decides (including UI)
- download option (including UI)
- adding support for an S3 bucket.
- support replacement of video file.

## Related issues

https://github.com/Chocobozzz/PeerTube/issues/733

## Has this been tested?

- [ ] 👍 yes, I added tests to the test suite
- [ ] 💭 no, because this PR is a draft and still needs work
- [ ] 🙅 no, because this PR does not update server code
- [x] 🙋 no, because I need help 

We would need some assurance regarding our approach, is it the correct approach, and what would be the best way to test it?

### CODE REVIEW

**Comment by Chocobozzz** [comment]
> We would need some assurance regarding our approach, is it the correct approach, and what would be the best way to test it?

Yes I think it is. I would just use only `keptOriginalFileName` (`keptOriginalFilename` for consistency with `videoFile` table for example) as if the column is `null` then we don't have this file.

Another question is where do we store such file.

You can follow https://docs.joinpeertube.org/support/doc/development/tests for a guide to write a PeerTube test (server tests will be enough)

**Comment by chagai95** [comment]
Thx for answering, so quick!  

> Another question is where do we store such file.

Until it's decided where is best to save the file we can just keep it there in the meantime or is that a problem?

We will remove `keptOriginalFile` and only use `keptOriginalFileName`.

Is there anything else we would need to do to get the PR merged besides getting the tests to run?

**Comment by Chocobozzz** [comment]
> Until it's decided where is best to save the file we can just keep it there in the meantime or is that a problem?

I think we should store them in a dedicated directory:
 * Easier to backup
 * We may not want to serve original videos like we do for classic videos (and so not serve them directly from nginx)
 * They are not web videos (they may be `.mkv` etc) and they are not HLS files so they should not belong to these directories

> Is there anything else we would need to do to get the PR merged besides getting the tests to run?

Yes, I think we need to support object storage for such files too as it would be complicated to add it in the future (how do we consider a video that has the original file stored on disk and the transcoded files in object storage?)

**Comment by chagai95** [comment]
Thx for clarifying! We added a new dedicated directory, changed to using only keptOriginalFileName, changed keptOriginalFileName to keptOrginalFilename (for consistency with videoFile table - lowercase) and began implementing object storage.

We might need some help with implementing `object storage`.

**Comment by Chocobozzz** [comment]
Hi @chagai95 

What's the status of this PR? :)

**Comment by chagai95** [comment]
I'm still hoping to make some progress with the object storage, but it will take us some time, if anyone else wants to pick it up, I don't want to be in the way, but we are still planning on getting this finished soon!

**Comment by mzero** [comment]
From the discussion here, it sounds like the original filename from the upload will be lost. It would be nice (and match the similar experience on sites like SoundCloud & BandCamp that allow original download) - if the original filename were retained, and what the user got when downloaded. It doesn't matter that it is UUID'd while in the storage system.

**Comment by Chocobozzz** [comment]
> From the discussion here, it sounds like the original filename from the upload will be lost.

No we keep it in the database and so use it as filename when the user downloads it :)

I'll work on this PR and add S3 support and tests

**Comment by Chocobozzz** [comment]
Thanks for the PR.

I added:
 * tests
 * object storage support
 * possibility for uploaders to download the original file
 * inclusion of the original file in the user export archive if available (instead of the max quality file)

**Pull request merged**
