### PR TITLE
Read server config in client

### LINKED ISSUE #4156: Custom landing page not working
**Describe the current behavior**
Setting a custom landing page won't have any effect.

**Steps to reproduce:**

1. Visit https://peertube.heraut.eu/
2. See that the landing page is trending instead of recently added (which you can see in the config).

**Describe the expected behavior**
Landing page config should be respected.

* PeerTube instance:
  * URL: https://peertube.heraut.eu/
  * version: 3.2.1

* Browser name, version and platforms on which you could reproduce the bug:
Chrome, latest

### PR DESCRIPTION
**Pull request by kontrollanten**
## Description
In this commit https://github.com/Chocobozzz/PeerTube/commit/aea0b0e7cde7495e60fe07b4444067f53d35ce3f#diff-b790b1328b693655155aecf1d184a7b7c1ab494e1383a6b1a208cd4e4b42fb99 the functionality seemed to have got broken. Just restoring what changed in there since it looks like some dev configuration.

## Related issues
closes #4156

## Has this been tested?

- [x] 👍 yes, light tests as follows are enough

1) Change landing page
1) Reload the page
1) Verify the new landing page is set

### CODE REVIEW

**Comment by Chocobozzz** [comment]
I don't understand: in https://github.com/Chocobozzz/PeerTube/issues/4156 you're talking about 3.2.1. 

https://github.com/Chocobozzz/PeerTube/commit/aea0b0e7cde7495e60fe07b4444067f53d35ce3f#diff-b790b1328b693655155aecf1d184a7b7c1ab494e1383a6b1a208cd4e4b42fb99 was not included in 3.2

**Comment by kontrollanten** [comment]
Okay, then it's some other issue with https://peertube.heraut.eu/ The custom landing page is only working the second page load, which this PR doesn't seem to fix.

**Comment by Chocobozzz** [comment]
So what is the issue you're fixing with this PR?

**Comment by kontrollanten** [comment]
It's fixing that the landing page works at least the second time

**Comment by Chocobozzz** [comment]
Should be fixed in develop

**Pull request closed without merging**
