### PR TITLE
Update FAQ.md

### PR DESCRIPTION
**Pull request by Jorropo**

### CODE REVIEW

**Comment by Nutomic** [comment]
Vuze also has webtorrent support: https://wiki.vuze.com/w/WebTorrent

**Comment by rigelk** [comment]
Linking to https://github.com/webtorrent/webtorrent/issues/369 instead of quoting each and every client is probably better. But even then you are missing `webtorrent-hybrid`, which is useful to stream videos in the cli for instance.

**Comment by Jorropo** [comment]
@rigelk I already thinked about telling of webtorrent hybrid but that seems too complicated for an FAQ.
And when you tell :
> Linking to webtorrent/webtorrent#369 instead of quoting each and every client is probably better.

You think that a sentence like that is better ?
You can find here a client list supporting webtorrent https://github.com/webtorrent/webtorrent/issues/369

**Comment by Jorropo** [comment]
@zig-03 correct me if I'm wrong (cause I'm french) another limit to one and other say multiple. Cause multiple servers can do redundancy. If yes I think other is better.

**Comment by Zig-03** [comment]
Hi @Jorropo 
if multiple servers can do the redundancy feature then the text would look something like this:
"It can also be helped by other servers using"

**Comment by Jorropo** [comment]
@Zig-03 effectively I forgoted it.

**Comment by Zig-03** [comment]
@Jorropo you missed one word "be"

> "It can also **be** helped by other servers using"

:)

**Comment by Jorropo** [comment]
@Chocobozzz @Zig-03 made !
:smile:

**Comment by Chocobozzz** [comment]
Thanks @Jorropo & @Zig-03

**Pull request merged**
