### PR TITLE
QR Code #683

### LINKED ISSUE #683: Add qr-code for video url
It would be great if we could have a qrcode displayed after to click on share button.
We could have : 
- url of video
- embed code
- qrcode

This  code could be easily downloaded in order to place it on documents for education (there is a lot of tablets on french schools).
qrcode is also a good solution because videos url are very long...

### PR DESCRIPTION
**Pull request by DeeJayBro**
Adding QR-Code to the Share Menu to close #683

### CODE REVIEW

**Comment by Chocobozzz** [comment]
Nice work @DeeJayBro thanks!

**Comment by bristow** [comment]
Nice, big thank @DeeJayBro !

Is there a way to see the merge in action ?

**Comment by Chocobozzz** [comment]
Tomorrow on peertube2.cpy.re

**Comment by rigelk** [comment]
A local example :wink: 

2018-07-12-qr

**Pull request merged**
