### PR TITLE
Add basic video editor support

### PR DESCRIPTION
**Pull request by Chocobozzz**
Features in this PR:
 * Add basic video editor support
 * Video editor is an opt-in setting
 * The following edition tasks are available: cut the video (new start/end), add intro/outro, add watermark
 * There is no video history, the current video files are replaced by the new video

We chose flexibility over performance, so PeerTube will execute 1 ffmpeg process per task (`cut`, then add an `intro` etc) instead of merging complex filters in only one process. It reduces potential bugs, and it's easier to add additional edition tasks in the future. We may imagine potential edition tasks added by plugins.

screen_2022-02-21-10:47:23

### CODE REVIEW

**Comment by klorydryk** [comment]
Hi,
Tried it and got an error:
"<html> <head><title>413 Request Entity Too Large</title></head> <body bgcolor="white"> <center><h1>413 Request Entity Too Large</h1></center> <hr><center>nginx/1.14.2</center> </body> </html> "

**Comment by klorydryk** [comment]
If i only sect the watermark, I got this error: "Video editor is disabled on this instance"

**Comment by Chocobozzz** [comment]
Hi,

> Tried it and got an error:
" <title>413 Request Entity Too Large</title> 

Thanks, I forgot to update the nginx template. Should be fixed by https://github.com/Chocobozzz/PeerTube/commit/5357ce93474b59bac9c7b1fbe4224e0f1fb7ea66

> Because it is disabled by default, but we are still able to access to it from "my-library/videos".

Should be fixed by https://github.com/Chocobozzz/PeerTube/commit/22e909224c023c10699fce5c8b9db4be2cd049d7

**Comment by klorydryk** [comment]
Hi ! I still have the "<html> <head><title>413 Request Entity Too Large</title></head> <body bgcolor="white"> <center><h1>413 Request Entity Too Large</h1></center> <hr><center>nginx/1.14.2</center> </body> </html>" error in 4.1.1-nightly-2022-03-24 XD

**Pull request merged**
