### PR TITLE
Add fcbk open-graph and twitter-card metas for accounts, video-channels, playlists urls

### PR DESCRIPTION
**Pull request by kimsible**
Fixes: https://github.com/Chocobozzz/PeerTube/issues/2989

Tests :

```bash
$ npm run build:server
$ NODE_ENV=test npm start

# Playlist 
$ curl http://localhost:9000/videos/watch/playlist/:uuid

# Account
$ curl http://localhost:9000/accounts/:username

# Channel
$ curl http://localhost:9000/video-channels/:name
```

og-fcbk-playlist
og-fcbk-channel
og-fcbk-account

### CODE REVIEW

**Comment by Chocobozzz** [comment]
Please fix lint tests and https://travis-ci.com/github/Chocobozzz/PeerTube/jobs/365185689 test

**Comment by kimsible** [comment]
> Please fix lint tests and https://travis-ci.com/github/Chocobozzz/PeerTube/jobs/365185689 test

I'll try but the tests still not work in local, maybe I should open an issue, it's a serious problem for contributions...

**Comment by Chocobozzz** [comment]
> I'll try but the tests still not work in local, maybe I should open an issue, it's a serious problem for contributions...

Yes please

**Comment by kimsible** [comment]
> Could you add tests for accounts, channels and playlists meta tags? https://github.com/Chocobozzz/PeerTube/blob/develop/server/tests/client.

I"ve added some tests, but I still have this problem with local tests https://github.com/Chocobozzz/PeerTube/issues/3022

> Maybe you could also refactor addAccountOrChannelOpenGraphAndMetaTags, addVideoPlaylistOpenGraphAndMetaTags and addVideoOpenGraphAndOEmbedTags methods that share some code

I've refactored all these methods.

**Comment by Chocobozzz** [comment]
Thanks

**Pull request merged**
