### PR TITLE
Rewrite prose for JavaScript disabled message

### PR DESCRIPTION
**Pull request by cloudrac3r**
## Description

This should improve the clarity of the message and make it easy to
understand what the problem is at a glance.

- Clearly show that the page is PeerTube, without having to read the whole prose
- Clearly show that the problem is JavaScript, without having to read the whole prose
- Reorganise suggestions into a bullet list

I figured this was trivial enough that I didn't need to open an issue for discussion first. Just let me know if you have comments :)

## Has this been tested?

Yes, manually, by loading the HTML file in a browser with scripts disabled, and checking that the page looked like what I wanted.

### CODE REVIEW

**Review by rigelk — APPROVED** [review]
I changed a few things along the way to simplify further maintenance.

**Comment by rigelk** [comment]
@cloudrac3r thanks! This is indeed simpler to read and act upon.

**Comment by cloudrac3r** [comment]
Did you test your changes? I found that `noscript` would be replaced with a `span`. So it couldn't be styled directly, and `max-width` wouldn't apply anyway since the element was inline. That's why I added the nested div.

**Comment by rigelk** [comment]
yes, I tested them the same way you did.

**Comment by cloudrac3r** [comment]
I can't get it to apply the styles, but I trust that you know more than me, so you're probably doing it right and I'm not. :) Thanks!

**Comment by rigelk** [comment]
what browser are you testing this with? Are you running the instance in a specific mode (dev? prod?)?

**Pull request merged**
