### PR TITLE
Generate OpenAPI client libraries

### PR DESCRIPTION
**Pull request by LoveIsGrief**
Related to #2052 "Publish OpenAPI clients" this pullrequest introduces a `openapi` stage in `.travis.yaml` that can be triggered either forcefully or by pushing a tag.  

# Stages

The [travis doc on stages](https://docs.travis-ci.com/user/build-stages/) explains the concepts.

**test**

All previous jobs in the `matrix:` are now in the `jobs:` dict and have been put into this stage. It is **activated by default** but can be deactivated by **`NO_TESTING`**=true in the repository setting (or environment variable)

**openapi**

This stage will generate and then publish the clients passed to the job on travis. 

# Client lib generation

The repository setting (or environment var) **`API_LANGS`** is a `:` delimited list of client libs to generate.
A list of possible clients can be found [here](https://github.com/OpenAPITools/openapi-generator/wiki/API-client-generator-HOWTO).

**Requirements**

A parameter config in the `/openapi` folder for the client e.g `/openapi/python.yaml`. The params can be generated by running the docker openapi-cli (see `/scripts/openapi-clients.sh`) e.g `openapitools/openapi-generator-cli config-help -g python`

# Client lib publication

The client lib will be pushed to a github repository of the format `"https://github.com/${API_GIT_USER}/${API_REPO_PREFIX}${lang}.git"`.

See `/scripts/openapi-clients.sh` for the required environment variables.

# Examples

https://github.com/LoveIsGrief/peertube-api-kotlin

https://github.com/LoveIsGrief/peertube-api-go

https://github.com/LoveIsGrief/peertube-api-python

# TODO in down the line

- versioning: each package config can have a version (maybe the same as peertube?)
- the python template doesn't like a multi-lined description (see the repo above and it will be glaringly obvious)
- Modify the `.travis.yaml` of each published client lib to:

   - run tests
   - publish to their package index

- List each published package in the API documentation.

### CODE REVIEW

**Comment by Chocobozzz** [comment]
Thanks. I will pull and update your branch to use gitlab ci schedules to generate these packages, and I'll create a `peertube-rest-api-packages` repository on framagit to put all the packages in the same repo (easier to maintain/link)

**Comment by LoveIsGrief** [comment]
Ah, I wasn't sure which one to use since there's also a `.gitlab-ci.yaml` in the repo. Didn't know which one took precedence.
How can I help publishing the packages to their respective indices (if it is needed at all)? I specifically need the Python client lib which is the major reason I started all of this. 
Thanks for considering this PR

**Comment by LoveIsGrief** [comment]
Hi @Chocobozzz, I checked https://framagit.org/framasoft/peertube and the `peertube-rest-api-packages` repo doesn't exist.

Should I lend a hand writing the `.gitlab-ci.yaml`?

**Comment by Chocobozzz** [comment]
Hi, sorry for the late. I create the repository: https://framagit.org/framasoft/peertube/peertube-rest-api-packages

Please create a MR on framagit :+1:

**Pull request closed without merging**
