### PR TITLE
Add Introduction to README (short explanation of what is PeerTube)

### PR DESCRIPTION
**Pull request by thomaskuntzz**
Provide small explanation of what is PeerTube and point to resources to learn more (combined with 'Want to see in action?' links)

I had a hard time coming up with a short and still decent explanation of what PeerTube is and how it works, feel free to improve it as you see fit 😉😊

### CODE REVIEW

**Comment by rigelk** [comment]
The introduction is halfway between the short text below the title and the motivation paragraph. We should be moving the motivation paragraph to the FAQ, referring to it in your introduction, and trying to not say twice what is said in the short text below the title.

**Comment by thomaskuntzz** [comment]
Oh, yeah, that's right, we could sort of combine these two. However I see that there are two FAQs, one in FAQ.md on GitHub and the other on joinpeertube.org. I feel it could be redundant, even though the one one GitHub seems more about technical topics than the other. What do you think?

**Comment by rigelk** [comment]
Indeed, but that redundancy of the FAQs is acceptable IMHO, since the one in GitHub is more technical, and the one on joinpeertube.org can be translated.

**Comment by thomaskuntzz** [comment]
Okay but then explaining the motivation behind the project would be more relevant on joinpeertube.org, wouldn't it?

**Comment by rigelk** [comment]
The motivation is relevant for both FAQs.

**Comment by rigelk** [comment]
In the end I'll reorganise the "Motivation" based on your changes. Thanks @thomaskuntzz !

**Pull request merged**
