### PR TITLE
prettify SQL queries during debug

### PR DESCRIPTION
**Pull request by rigelk**
## Description

Debugging SQL queries is never easy, so easing their read would be welcome 🙂 

## Screenshots

Screenshot from 2021-01-24 20-35-36

### CODE REVIEW

**Comment by Chocobozzz** [comment]
LGTM. Weird the tests fail :thinking: (I re ran them)

**Comment by rigelk** [comment]
@Chocobozzz timeouts seem to be impacted?

**Comment by Chocobozzz** [comment]
I'll debug that

**Comment by rigelk** [comment]
Thanks

**Comment by Chocobozzz** [comment]
Your prettifier is too slow, I replaced it by the origin prettifier (that does not have colors but it's better than nothing).

**Pull request merged**
