### PR TITLE
Fix documentation:

### PR DESCRIPTION
**Pull request by JohnXLivingston**
## Description

The documentation says "reload" instead of "start" or "restart".

### CODE REVIEW

**Comment by Chocobozzz** [comment]
The post certbot hook has not already restarted nginx?

**Comment by JohnXLivingston** [comment]
> The post certbot hook has not already restarted nginx?

Hum...
I did not check. It just seemed wrong to me. Maybe you are right.

**Comment by PaliPalo** [comment]
I've read that `--post-hook` works only with the `renew` action. So this command `--pre-hook ..` should be removed and the `start` should be done instead of `reload` (just `start` no need to stop nginx twice since the `stop` is done before `certbot`)

**Comment by Chocobozzz** [comment]
Let's change this to `restart` then, just in case ;)

**Comment by JohnXLivingston** [comment]
Here you go :)

**Comment by Chocobozzz** [comment]
Thanks @JohnXLivingston :pray:

**Comment by JohnXLivingston** [comment]
> Thanks @JohnXLivingston 🙏

That was a hard work, now i need to rest ;)

**Pull request merged**
