### PR TITLE
Feature/admin responsability

### PR DESCRIPTION
**Pull request by Chocobozzz**
screen_2019-09-03-11:25:10
screen_2019-09-03-11:25:03
screen_2019-09-03-11:24:34
screen_2019-09-03-11:24:23

### CODE REVIEW

**Comment by Chocobozzz** [comment]
Added some screens

**Comment by Nutomic** [comment]
Looks good! I also added some info about technical details (server provider etc) [on my instance](https://peertube.social/about/instance), maybe we could add a field for that too? Or an option to add extra fields?

Can this info be edited by mods, or only by admins? And could you add a screenshot how users see this info?

**Comment by Chocobozzz** [comment]
> Looks good! I also added some info about technical details (server provider etc) on my instance, maybe we could add a field for that too?

It's a good idea. I'll add it. 

> Can this info be edited by mods, or only by admins?

Only by admins

> And could you add a screenshot how users see this info?

screen_2019-09-04-16:35:01
screen_2019-09-04-16:34:27

**Comment by mayel** [comment]
Will this information be made available via an API, such as nodeinfo or in some ActivityPub endpoint? It would be great because we plan on implementing something similar for [MoodleNet](https://new.moodle.net/) and would be nice to make it interoperable. It would also allow for fediverse directory sites to index and display this information.

**Comment by Chocobozzz** [comment]
I don't think there is a standardized place where we could put these information. For now it will be in our REST API: `/api/v1/about`. But if we find a place to put them, we'll do it :+1:

**Comment by mayel** [comment]
Great :) nodeinfo2 might be an option? I've opened an issue there about adding fields: https://git.feneas.org/jaywink/nodeinfo2/issues/2

**Comment by jaywink** [comment]
Hey, just to sync my reply here as well:

---

> Hi @mayel ! I think it's a good idea to provide a possibility for admins to provide extra information about their instance. This is after all one of the reasons for NodeInfo type documents being created.
> 
> NodeInfo2 was a kind of temporary step towards something that would be better thought out and truly cross-protocol compatible. I've been drafting a thing called ServerInfo (but will be renamed to ServiceInfo in the next draft). I think it makes sense to push that forward instead of iterating on NodeInfo2. I believe we can get a longer lasting result. I also intend to submit the next draft for comments to the SocialCG group.
> 
> You can see the discussion and link to the draft in our Forum: https://talk.feneas.org/t/serverinfo-specification-for-server-metadata/99
> 
> Opinions would be very much welcome! I'll anyway have a peek into the linked PR on PeerTube and try incorporate those ideas into the next draft, based on this feedback.
> 
> I hope to build a working parser and serializer for the next draft soon as well to get some live working versions out there.
> 
> Does this sound good to you?

**Pull request merged**
