### PR TITLE
Update FreeBSD startup script

### PR DESCRIPTION
**Pull request by gegeweb**
Adding procname='node:' to find pid for stopping the service launched with node.
Previous version doesn't work without this since the upgrade to FreeBSD 11.2.

### CODE REVIEW

**Comment by rigelk** [comment]
Thanks @gegeweb!
Could you explain your changes in the PR or commit description?

**Comment by gegeweb** [comment]
I'v just add to line, since the upgrade to FreeBSD 11.2 stopping the service with `service stop pertube`doesn't works. Processus pid not find.
So I've add 'procname='node:' to deal with.

It works now on my system, I can do restart or stop succefully.

**Comment by Chocobozzz** [comment]
Thanks @gegeweb

**Comment by gegeweb** [comment]
Well... it doesn't work as expected.
If there are other process nodes, stopping the service will kill all process nodes, even if it is not Peertube.
I can't figure out how to get the pid number... I'll figure out how to do it!

**Comment by rigelk** [comment]
@gegeweb then please open an issue tracking the problem so that we don't forget it exists.

**Comment by gegeweb** [comment]
@rigelk  Done! #1477

**Pull request merged**
