### PR TITLE
improve mobile compatibility on mobile screens

### PR DESCRIPTION
**Pull request by test2a**
updated more pages to fit to mobile

### CODE REVIEW

**Comment by test2a** [comment]
i used gitpod to make these changes and i am not sure if i did a mistake..... please be kind :-)

**Comment by rigelk** [comment]
@test2a please at the very least use a descriptive title, and fix errors reported by the linter before submitting a PR.

**Comment by test2a** [comment]
gitpod is not showing me errors

**Comment by rigelk** [comment]
The PR linter is.

**Comment by kontrollanten** [comment]
> gitpod is not showing me errors

@test2a run `npm run lint` and you'll see the errors. Here you can read about how to do that in gitpod https://www.gitpod.io/docs/languages/javascript/

**Comment by Chocobozzz** [comment]
I think the `width: 100%` should be included in the mixins, using `max-width: 100%` for example :thinking:

**Comment by test2a** [comment]
this is whats in use in other pages like login or signup. i just added the same to playlist and channels

**Comment by rigelk** [comment]
@test2a could you fix the linting errors please?

**Comment by test2a** [comment]
@rigelk unfortunately i am away from my home, no laptop in sight. i can just delete this pr and someone else could redo it or pick this one?

**Comment by rigelk** [comment]
> @rigelk unfortunately i am away from my home, no laptop in sight. i can just delete this pr and someone else could redo it or pick this one?

alright. You can request a reopening later too once this is fixed.

**Pull request closed without merging**
