### PR TITLE
Change copy icon

### PR DESCRIPTION
**Pull request by kontrollanten**
## Description
1) Replaces `icon-copy` with `icon-duplicate` since the latter is more common (https://www.google.com/search?q=copy+icon&source=lnms&tbm=isch&sa=X&ved=2ahUKEwiI1OS1rpLvAhVpkosKHfrTBAQQ_AUoAXoECBQQAw&biw=1650&bih=819)
1) Adds "Copy" text next to the icon when used in input fields.

## Related issues
* #3810 

## Has this been tested?

- [x] 👍 yes, light tests as follows are enough

1) Visit a video page and open share modal.
1) Visit a video page and open download modal.
1) Visit an account page and check "copy account name" icon.
1) Visit a video channel page and check "copy channel name" icon.

## Screenshots

image
image
image
image

### CODE REVIEW

**Comment by Chocobozzz** [comment]
The icon is bigger. Did you have users that did not understand the former icon?

**Comment by kontrollanten** [comment]
> The icon is bigger.

I haven't changed the size, but I can decrease it if you'd like. 

>  Did you have users that did not understand the former icon?

Yes, we've some users that didn't understand it.

**Comment by rigelk** [comment]
@kontrollanten please decrease the icon size to match the former line-height.

**Comment by kontrollanten** [comment]
Update:

image

image

image

image

**Comment by Chocobozzz** [comment]
Thanks @rigelk @kontrollanten

**Pull request merged**
