### PR TITLE
Fix AutoThread

### PR DESCRIPTION
**Pull request by Jorropo**
Sorry, I will test next times, I didn't know why I didn't do it for auto thread.
And I don't know how to change using zanata. (And there is missing setance in zanata cause I finished the last 7% of french yesterday but there is staying some english)

### CODE REVIEW

**Comment by rigelk** [comment]
@Jorropo isn't it "should be greater *or equal* to 0" then?

**Comment by Jorropo** [comment]
@rigelk made, I also win to do an :
```sh
npm run i18n:generate
```

**Comment by rigelk** [comment]
@Jorropo please don't generate/modify the generated translation ; this is done automatically when releasing.

**Comment by Jorropo** [comment]
@rigelk ok

**Comment by Chocobozzz** [comment]
Thanks @Jorropo

**Pull request merged**
