### PR TITLE
Fix: make truncated moderation table field (video title) fully visible

### PR DESCRIPTION
**Pull request by kimsible**
Issue: https://github.com/Chocobozzz/PeerTube/issues/2018

Before: 
title-moderation-before

After:
title-moderation

### CODE REVIEW

**Comment by rigelk** [comment]
I would rather have the title attribute set if it isn't already the case, and/or make sure the thumbnail doesn't change size.

**Comment by kimsible** [comment]
> I would rather have the title attribute set if it isn't already the case, and/or make sure the thumbnail doesn't change size.

Thanks @rigelk, it seems it changes the thumbnail size that way :-(.

**Comment by rigelk** [comment]
I replaced the title value with the video name. Though not mobile-friendly, it still improves the situation for small screens.

**Comment by kimsible** [comment]
Thanks for this @rigelk ! I totally forgot that PR btw.

**Pull request closed without merging**
