### PR TITLE
#5618 - Configuration fields for Thumbnails and Previews

### PR DESCRIPTION
**Pull request by gergob**
## Description

Feature Change:
1. Updated the configurations, so `Thumbnail` and `Preview` image sizes can be configured in `yaml` files. In case the configuration is not there, there are some defaults left there.

## Related issues

https://github.com/Chocobozzz/PeerTube/issues/5618

## Has this been tested?

- [x] 👍 yes, I added tests to the test suite
- [ ] 💭 no, because this PR is a draft and still needs work
- [ ] 🙅 no, because this PR does not update server code
- [ ] 🙋 no, because I need help 

## Test resuts

```text
> peertube@6.1.0 mocha
> mocha --exit --bail packages/tests/src/api/server/config.ts



  Test static config
    ✔ Should tell the client that edits are not allowed (48ms)
    ✔ Should error when client tries to update

  Test config
    Config keys
      ✔ Should have the correct default config
      ✔ Should have a correct config on a server with registration enabled
      ✔ Should have a correct config on a server with registration enabled and a users limit (168ms)
      ✔ Should have the correct video allowed extensions
      ✔ Should get the customized configuration
      ✔ Should update the customized configuration
      ✔ Should have the correct updated video allowed extensions (1274ms)
      ✔ Should have the configuration updated after a restart (933ms)
      ✔ Should fetch the about information
      ✔ Should remove the custom configuration
      ✔ Should enable/disable security headers (995ms)
    Image files
      Banner
        ✔ Should update instance banner (434ms)
        ✔ Should re-update an existing instance banner (114ms)
        ✔ Should remove instance banner
      Avatar
        ✔ Should update instance avatar (930ms)
        ✔ Should have the avatars in the AP representation of the instance
        ✔ Should remove instance avatar
        ✔ Should not have the avatars anymore in the AP representation of the instance


  20 passing (10s)
```

## Screenshots

peertube-image-size-changes

### CODE REVIEW

**Comment by Chocobozzz** [comment]
Thanks! Rebased manually in https://github.com/Chocobozzz/PeerTube/commit/3fbe84918392141e16976b952932e7eac10e99be & https://github.com/Chocobozzz/PeerTube/commit/1e3a5b25c367b47e49808b443c504769db21ebe6

**Comment by gergob** [comment]
@Chocobozzz thank you!

**Comment by Sakrecoer** [comment]
Apologies if i am doing this wrong.. This issue is mentioned in the release notes of 6.2.0. However, these settings does not seem to be present in the latest version of [default.yaml](https://github.com/Chocobozzz/PeerTube/blob/18f13f43ec6f17df457d6cf61e5030179670949c/config/default.yaml#L470) After upgrade from `6.1.0` to `6.2.0`, it was also not present in `production.yaml.new`

**Comment by gergob** [comment]
@Sakrecoer FYI, here is a sample config, which you can use:

```yaml
thumbnails:
  generation_from_video:
    # How many frames to analyze at the middle of the video to select the most appropriate one
    # Increasing this value will increase CPU and memory usage when generating the thumbnail, especially for high video resolution
    # Minimum value is 2
    frames_to_analyze: 80
  sizes:
    - width: 1280
      height: 720

    - width: 1280
      height: 720
```

**Pull request closed without merging**
