### PR TITLE
Fix subtitle download issue, ensure subtitles download as .srt files

### PR DESCRIPTION
**Pull request by sanjayr-12**
## Description

This PR resolves the problem where subtitles were opening in a new tab instead of downloading as a file.

**Changes**:
- Updated the subtitle download logic to use `fetch` and `blob` for proper file download.
- Ensured that the downloaded file has the correct `.srt` extension.

## Related issues

Resolves: #6623

## Has this been tested?

- [ ] 👍 yes, I added tests to the test suite
- [ ] 💭 no, because this PR is a draft and still needs work
- [x] 🙅 no, because this PR does not update server code
- [ ] 🙋 no, because I need help

### CODE REVIEW

**Comment by Chocobozzz** [comment]
Hi & thank you for your work :pray: 

But please use the same methods as other downloads: 
 * Create a controller to download a subtitle https://github.com/Chocobozzz/PeerTube/blob/develop/server/core/controllers/download.ts#L43
 * Add this URL in the caption API: `captionDownloadUrl`
 * Use it it the frontend

**Comment by Chocobozzz** [comment]
Closing due to inactivity. Do not hesitate to ask for the reopening :)

**Comment by ROBERT-MCDOWELL** [comment]
@sanjayr-12  @Chocobozzz 
is a PR or is it solved already?

**Comment by sanjayr-12** [comment]
> @sanjayr-12 @Chocobozzz is a PR or is it solved already?

It is not solved yet. I started working on it but am still learning and trying to understand certain aspects of things.

**Pull request closed without merging**
