### PR TITLE
User subscriptions

### PR DESCRIPTION
**Pull request by Chocobozzz**
* Add ability to set the name of the channel
 * We will try to put more emphasis on channels in the future (instead of accounts)
 * Add subscriptions tab in the menu, to see videos from subscriptions
 * Add ability to subscribe to a video channel
 * Add subscriptions tab in user menu, to see subscribed video channels
 * Add some channels in search results
 * Add ability to search remote video or video channels (from a URL or handle) if allowed by the administrator (by default, only logged users can do that)
 * When we search a remote object, we fetch it and insert it in the database. If it is an actor, we process its outbox in a job (to create videos etc). Since we might not follow these actors, we need to refresh them sometimes

### CODE REVIEW

**Comment by Chocobozzz** [comment]
@Jorropo yes for the `@app` in fact I use the auto import so sometimes it decides to use it, sometimes it doesn't ^^

> I have just a question (this isn't a problem of using name instead of uuid for channel (why can't we get conflict ?))

I'm sorry I don't understand the question. You fear conflicts on actor names?

**Comment by Jorropo** [comment]
@Chocobozzz yeah, I fear that.

**Comment by Chocobozzz** [comment]
@Jorropo I don't think so, we just detect conflicts when someone tries to create a user or a channel with an existing name. See https://github.com/Chocobozzz/PeerTube/issues/640

**Comment by Chocobozzz** [comment]
Done, I updated the PR description.

**Pull request merged**
