### PR TITLE
sensitive-content issue fix

### PR DESCRIPTION
**Pull request by smilekison**
## Description

This PR is related to the feature requested in oembed system. This PR solves the issue related to issue https://github.com/Chocobozzz/PeerTube/issues/3419 .

## Has this been tested?

- [ ] 👍 yes, I added tests to the test suite
- [ ] 💭 no, because this PR is a draft and still needs work
- [ ] 🙅 no, because this PR does not update server code
- [X] 🙋 no, because I need help: The expected output changes everytime.

## Screenshots
The screenshot shows how the video will look like in the embedded system. 
Sensitive (NSFW): true
image

Sensitive (NSFW): false
image

### CODE REVIEW

**Comment by Chocobozzz** [comment]
Hello,

I'm sorry but the NSFW blur should be implemented in the embed page, not in the service that provide the iframe

**Comment by smilekison** [comment]
Hello,
I guess in messaging application (Slack or Mattermost), there is no way of implementing NSFW to blur video except blurring the iFrame or redirecting user to website. If there is can you please provide me some idea?

**Comment by smilekison** [comment]
> Hello,
> 
> I'm sorry but the NSFW blur should be implemented in the embed page, not in the service that provide the iframe

Hello,
I guess in messaging application (Slack or Mattermost), there is no way of implementing NSFW to blur video except blurring the iFrame or redirecting user to website. If there is can you please provide me some idea?

**Comment by Chocobozzz** [comment]
I'm not sure to understand the question: the embed page fetches de video so it knows if the video is NSFW or not

**Comment by smilekison** [comment]
I am sorry, Can you elaborate on the embed page?

Embed page meaning 3rd party place where the embed link is pasted? 

In the code, we are not passing nsfw value in OEmbed.
image

**Pull request closed without merging**
