### PR TITLE
Load Config Before Doing Anything Else

### PR DESCRIPTION
**Pull request by own3mall**
Fix for https://github.com/Chocobozzz/PeerTube/issues/1737

### CODE REVIEW

**Comment by Chocobozzz** [comment]
It's weird `loadConfig` is not finished in the `signup` function :thinking: It should be fast.

**Comment by own3mall** [comment]
You can't ensure timing on async operations, and if you look at the link to stackoverflow I included in the source code, you'll see it's a common problem and that the way I did it is the correct way to handle loading the config.  

https://stackoverflow.com/questions/39033835/angularjs2-preload-server-configuration-before-the-application-starts

**Comment by Chocobozzz** [comment]
Then prefer using `switchMap` [here](https://github.com/Chocobozzz/PeerTube/blob/develop/client/src/app/signup/signup.component.ts#L53).

This way you don't block the app until the configuration is loaded.

**Comment by own3mall** [comment]
It's not just the signup page though.  It could be any endpoint or page.  When it comes to loading the settings, it really should load the config first before doing anything else.  Plus, you said the call should be quick, and it is.  And, after this call is made, it is just referenced from localStorage, so I really don't see it being a bad thing.

**Comment by Chocobozzz** [comment]
We'll wait the config in these pages then. I don't want the app to wait 1 endpoint if this is not required for most pages.

**Comment by own3mall** [comment]
That's the whole point.  It could happen on any page, and there's no guarantee the load config call will be completed in time with the way it's currently setup in the main branch.  Up to you if you want to leave it completely broken in the main branch :-1: .  It's fixed in mine though.  :+1:

**Comment by Chocobozzz** [comment]
Fixed in https://github.com/Chocobozzz/PeerTube/commit/f3ae606caf74c8a173ce44bf3f913f1488f97d7f

**Pull request closed without merging**
