### PR TITLE
Translate more strings in player stats

### PR DESCRIPTION
**Pull request by emansom**
## Description

Translates more strings inside the player statistics.

## Has this been tested?

- [ ] 👍 yes, I added tests to the test suite
- [ ] 💭 no, because this PR is a draft and still needs work
- [x] 🙅 no, because this PR does not update server code
- [ ] 🙋 no, because I need help

### CODE REVIEW

**Comment by emansom** [comment]
Failed API tests can be ignored, they hit the timeout limit unrelated to this PR.

**Comment by Chocobozzz** [comment]
Hi,

Thanks for the PR. Please prefer to use placeholders (`{1} peers` for example) instead of building manually the strings.
Can you also revert your changes on translation files? It's automatically done when we update translations.

**Comment by emansom** [comment]
> Hi,
> 
> Thanks for the PR. Please prefer to use placeholders (`{1} peers` for example) instead of building manually the strings. Can you also revert your changes on translation files? It's automatically done when we update translations.

Done https://github.com/Chocobozzz/PeerTube/pull/5256/commits/c290244c497003523353da73ef663fc08654a1a7 👍🏻

**Comment by Chocobozzz** [comment]
Thanks!

**Pull request merged**
