### PR TITLE
Enh #106 : Add an autoPlayVideo user attribute

### PR DESCRIPTION
**Pull request by dedesite**
!!! WARNING : I was not able to run the tests on my machine. It uses a different approach to handle databse connexion and didn't find where to configure it... please run the tests before and don't kill me if they don't pass... and also help me running my tests :)

- create a migration file to add a boolean column in user table
- add autoPlayVideo attribute everywhere it is needed (both on client and server side)
- add tests
- add a way to configure this attribute in account-settings
- use the attribute in video-watch component to actually autoplay or not the video

Note: it was quite a pain to include a simple attribute to the user. User's data structure is declared multiple times and checks are also done at different places. It feels like things could be made implicit and not always explicit (ie copy the entire objet instead of each attributes) but I'm new to the project, I may miss some important constraints.

### CODE REVIEW

**Comment by dedesite** [comment]
I realize that this PR is quite "big", tell me if you want it to be cut into several commits.

**Comment by Chocobozzz** [comment]
Wonderful!

Tests configurations are defined in `config/test-1.yaml`, `config/test-2.yaml`... and they inherit `config/test.yaml` and `config/default.yaml`. So just `createdb peertube_test{1,2,3,4,5,6}` and this should work.

Yes, the user attributes are replicated in different places:
 * In the database model
 * In the shared interface
 * In the client that implements the interface to represent a classic user
 * In the client that implements the interface to represent a authenticated user

I think I could try to refractor this, but there will still be at least 3 files (database model, interface and client model that implement some methods only used by the client).

**Comment by Chocobozzz** [comment]
There is just a small issue with the lint (https://travis-ci.org/Chocobozzz/PeerTube/jobs/318334735). Please fix it and we will able to merge :)

**Comment by dedesite** [comment]
Hello, I fixed the tslint issues but still struggle to launch the tests. I created the databases but the error is about user used to connect to the db. It takes my unix name and I use `postgres` user.
I'm not very familiar with PostgreSql though...

Thank you for your reply about the user attribute, I have some ideas about that but that'll come in another time, for now let's fix some issues :).

**Comment by Chocobozzz** [comment]
Maybe the travis configuration could help you: https://github.com/Chocobozzz/PeerTube/blob/develop/.travis.yml#L31

Don't hesitate to come on IRC (#peertube on freenode)

**Pull request merged**
