### PR TITLE
Remove the eventual trailing '/' at the end of urls (see #1453)

### PR DESCRIPTION
**Pull request by HesioZ**
This is my solution for the '/' at the end of urls which create problems in the import videos script (issue #1453).
I forgot to open a pull request for this.
The issue was closed yersterday but is the problem resolved or not ? Cause I haven't seen any proposal to solved it.
Maybe, it wasn't a real problem.

Thanks.

### CODE REVIEW

**Comment by Chocobozzz** [comment]
Thanks @HesioZ, but please fix code format: https://travis-ci.org/Chocobozzz/PeerTube/jobs/467150776

**Comment by HesioZ** [comment]
I've fixed code format but now there is a new error. I don't know how to solved it. 
Can someone help me, please ?

**Comment by rigelk** [comment]
Sounds like the kind of timeout that happens from time to time ; I'll trigger a retry.

**Comment by HesioZ** [comment]
Thanks!

**Pull request merged**
