### PR TITLE
Handle network issues in video player

### LINKED ISSUE #4782: Handle network issues appropriate in media player
**Describe the current behavior**
When watching a HLS video and the internet connection goes offline the player just becomes black with a spinner.

**Steps to reproduce:**

1. Visit https://peertube.cpy.re/w/rjy7vLphL2DL4gFA73twWN
2. Set the network connection to offline
3. Start the video

**Describe the expected behavior**
A user friendly message should be shown describing the issue and let them restart the video. Maybe the message should just be shown and then we're waiting for the network issue to be solved, and then automatically continue the video.

* PeerTube instance:
  * URL: https://peertube.cpy.re/w/rjy7vLphL2DL4gFA73twWN

* Browser name, version and platforms on which you could reproduce the bug: Latest Brave
* Link to browser console log if relevant:

```
hls-plugin.ts:255 HLS.js error: networkError - fatal: false - levelLoadError {type: 'networkError', details: 'levelLoadError', fatal: false, url: 'https://peertube2.cpy.re/static/streaming-playlist…7ba/cd0ba4ee-9763-44b4-a66f-3550eaf987ba-480.m3u8', loader: T, …}
hls-plugin.ts:226 trying to recover network error
VM205:1 GET https://peertube2.cpy.re/static/streaming-playlists/hls/cd0ba4ee-9763-44b4-a66f-3550eaf987ba/cd0ba4ee-9763-44b4-a66f-3550eaf987ba-480.m3u8 net::ERR_INTERNET_DISCONNECTED
...
peertube-player-manager.ts:212 Fallback to webtorrent.
VM205:1 GET https://peertube2.cpy.re/static/streaming-playlists/hls/cd0ba4ee-9763-44b4-a66f-3550eaf987ba/cd0ba4ee-9763-44b4-a66f-3550eaf987ba-480.m3u8 net::ERR_INTERNET_DISCONNECTED
...
webtorrent-plugin.ts:340 Error: http error from xs param: https://peertube.cpy.re/lazy-static/torrents/0ac21bb2-2479-4ef7-b549-b15cee21b745-480-hls.torrent
index.js:64 WebSocket connection to 'wss://peertube2.cpy.re/tracker/socket' failed: 
webtorrent-plugin.ts:340 Error: Error connecting to wss://peertube2.cpy.re/tracker/socket
```

### PR DESCRIPTION
**Pull request by kontrollanten**
## Description
Handle network issues in video player.

* Offline handling
* Fallback to other resolution upon network error
* Display user friendly interface upon unresolved error

## Related issues
closes #4782

## Has this been tested?

- [x] 🙅 no, because this PR does not update server code

## Screenshots
image

### CODE REVIEW

**Comment by emansom** [comment]
I would be very grateful if you implemented some logic that retries on [HTTP status code `429` (Too Many Requests)](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/429).

Taking the amount of seconds to wait for before a retry is attempted from the response header `Retry-After`, if available.

**Comment by emansom** [comment]
> It seems that the status code isn't in the actual error object, it seems like a hls.js bug. [video-dev/hls.js#4852](https://github.com/video-dev/hls.js/issues/4852)
> 
> After thinking a bit that may be a separate issue since a 429 response will probably affect the user, and I think they be informed that it isn't working as expected. Do you have a proxy that respond 429 or why are you experiencing that? It doesn't seem that PeerTube are having any rate limit on the static files.

Thanks for looking into it! 👍🏻 

HTTP Status Code 429 is intended as a form of rate limiting. It tells clients to retry automatically after a cool off period, adhering to the `Retry-After` instructions sent by the server.

I've configured my own PeerTube instance to send the 429 status code when requests per second on video fragments exceed a certain amount, nullifying attempts to leech bandwidth by malicious user agents.

An adjustment I made to the NGINX configuration after discovering a malicious client was DoSing by requesting fragments from various IP addresses at once.

It can sometimes be triggered by skipping segments really fast as well, which leads to a bad user experience; crashing the player.

Made the following adjustments to the NGINX configuration. Will upstream this once I settled on the best request rate. Lower it (and/or remove burst) to trigger the 429:

Within the `http { }` block inside `nginx.conf` place:
```nginx

  limit_conn_zone $binary_remote_addr zone=peertube_video_ip:10m;
  limit_conn_zone $server_name zone=peertube_video_total_conn:10m;

  # decrease rate below to trigger 429
  limit_req_zone $binary_remote_addr zone=peertube_video:10m rate=3r/s;

  limit_req_status 429;
  limit_conn_status 429;
```

Within the `server { }` block ensure the video fragments `location { }` block inside `/etc/nginx/conf.d/domain.tld.conf` contains this:
```nginx
    location ~ ^/static/(webseed|redundancy|streaming-playlists)/ {
        limit_conn peertube_video_total_conn 10000;
        limit_conn peertube_video_ip 10;

        # adjust or delete burst and delay to trigger 429 sooner
        limit_req zone=peertube_video burst=4 delay=2;

        limit_rate_after 5M;
        set $peertube_limit_rate 800k;

        if ($request_uri ~ -fragmented.mp4$) {
            set $peertube_limit_rate 5M;
        }
        limit_rate $peertube_limit_rate;
```

**Comment by Chocobozzz** [comment]
Hi,

Can you explain why a specific resolution could be broken?

**Comment by emansom** [comment]
Another usecase could be for example when watching using a spotty 4G LTE connection.

**Comment by Chocobozzz** [comment]
Thanks!

**Pull request merged**
