### PR TITLE
Add support of img bot (auto image compression)

### PR DESCRIPTION
**Pull request by Jorropo**
Img bot is an open source github integrated app that automatically make loss less image compression (proposed by PR).
ps : you need to subscribe to the github app (free) [github.com/marketplace/imgbot](https://github.com/marketplace/imgbot)
A commit in this PR is from ImgBot for allows you to see what it does.

### CODE REVIEW

**Comment by Chocobozzz** [comment]
Thanks for the PR @Jorropo but I prefer to do it manually (it's better to see differences, we know what we do, less dependent on another cloud based service etc)

**Comment by Jorropo** [comment]
ok :)

**Comment by Chocobozzz** [comment]
If you spotted images that could be optimized do not hesitate to create an issue :)

**Comment by Jorropo** [comment]
Made ! You can find it on #822

**Pull request closed without merging**
