### PR TITLE
Update video duration string to show hours when duration greater than or equal 60min

### PR DESCRIPTION
**Pull request by lucas-dclrcq**
Simple change to displayed video duration : show it as ```HH:MM:SS``` instead of  ```MMM:SS``` when duration is greater than or equal 60min.

Fixes: #356

### CODE REVIEW

**Comment by tcitworld** [comment]
Not sure we need hours padding here, it takes place for nothing.

**Comment by lucas-dclrcq** [comment]
Question : for now I'm displaying ```00:``` for hours when the duration is less than 60 min. Is it correct or do we want to only show the hours part when duration is greater than 60 min ?

It's would be less consistent across thumbnails, but the user would only see relevant numbers (Youtube shows video duration that way).

**Comment by lucas-dclrcq** [comment]
@tcitworld ok i'll remove hours padding

**Comment by tcitworld** [comment]
Yeah, hours should also be hidden when not useful.

**Pull request merged**
