### PR TITLE
Update production.md

### PR DESCRIPTION
**Pull request by DontUseGithub**
small inconsistency fix

### CODE REVIEW

**Comment by Chocobozzz** [comment]
I don't understand the purpose of this PR

**Comment by DontUseGithub** [comment]
The patter on that page is like this - bold & big text and then from a new line is the regular text, example:

### **Database**

Create the production database and a peertube user inside PostgreSQL:

____

But those two situations from the PR are different, they're in line:

**FreeBSD** On FreeBSD you can use Dehydrated security/dehydrated for Let's Encrypt

____

But should be like this:

### **FreeBSD** 

On FreeBSD you can use Dehydrated security/dehydrated for Let's Encrypt

**Comment by DontUseGithub** [comment]
The pattern on that page is like this - bold & big text and then from a new line is the regular text, example:

### **Database**

Create the production database and a peertube user inside PostgreSQL:

____

But what we currently have is this (they're in line):

**FreeBSD** On FreeBSD you can use Dehydrated security/dehydrated for Let's Encrypt

____

But should be like this:

### **FreeBSD** 

On FreeBSD you can use Dehydrated security/dehydrated for Let's Encrypt

____

BTW, why have you deleted that META issue? That is important. I remeber in Chocobozzz/PeerTube
there was a closed issue about SEO. Now if you search for it, you [won't find it](https://github.com/Chocobozzz/PeerTube/search?q=seo&type=Issues). I bet that person has deleted his account. Who knows how many more issues like these will just get lost.

**Comment by Chocobozzz** [comment]
Please check your changes then, it breaks production.md file.

**Pull request closed without merging**
