### PR TITLE
Bucket policy as an alternative for ACLs

### PR DESCRIPTION
**Pull request by Kinuseka**
## Description

Currently peertube uses ACLs to restrict access to direct video links to the bucket. 
However since ACL is a legacy feature, it is often not added by the some object storage provider (even the best ones e.g. backblaze). 
This PR aims to use Bucket policy instead to restrict access to videos on direct links due to wide compatibility.

## Related issues
solves #5497

## Has this been tested?

tested on staging app [testvid.kinuseka.us](https://testvid.kinuseka.us)

- [ ] 👍 yes, I added tests to the test suite
- [ ] 💭 no, because this PR is a draft and still needs work
- [ ] 🙅 no, because this PR does not update server code
- [ ] 🙋 no, because I need help 

# Goals and tests 🏁
- ✔ Toggable feature
- ✔ Changes policy 
- ✔ Adds video to policy and removes it when public
- ✔ Automatically adds policy when bucket policy is empty
- ❌ Identifies deny and allow (for now the program assumes `Policy.Statement[1]` is the Deny part of the policy)

# Efficiency 🔋
- ✔ HLS Per prefix policy
- ❌ Live Per prefix policy (For now it will keep appending the .ts files if live is private mode)
- ❌ Single folder private (Good for MinIO)

Template policy where this PR works on:
```json
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Principal": {
                "AWS": [
                    "*"
                ]
            },
            "Action": [
                "s3:GetObject"
            ],
            "Resource": [
                "arn:aws:s3:::vidtest/*"
            ]
        },
        {
            "Effect": "Deny",
            "Principal": {
                "AWS": [
                    "*"
                ]
            },
            "Action": [
                "s3:GetObject"
            ],
            "Resource": [
                "arn:aws:s3:::vidtest/favicon.ico" 
            ]
        }
    ]
}
```
since Bucket policy requires to have atleast 1 Resource in there, I just added favicon.ico as a temporary file

### CODE REVIEW

**Comment by emansom** [comment]
Is this compatible with Ceph and MinIO?

**Comment by Kinuseka** [comment]
> Is this compatible with Ceph and MinIO?

Yep! I made this PR because I was fraustrated with lack of compatibility of ACLs from MinIO

**Comment by emansom** [comment]
This PR is adding some S3 protocol level functionality, could this be deferred to a third party library instead?
Would lower the maintenance burden on Framasoft somewhat, potentially.

**Comment by Kinuseka** [comment]
I am trying to make this as flexible as possible by just adjusting how the ACL works and translating it into a bucket policy.
Both of these are configurable on CONFIGS, so if their bucket works with ACL, keep it enabled and the if the latter enable bucket policy. 

It is hard to rely on other obscure s3 compatible providers since they often 
lack the functionality crucial for the program or they have the functionality but does not work correctly.

If you mean we could merge this Bucket policy + ACL + (any other privacy methods) into a one giant library, which handles it. 

```
Step 1: If ACL fail try step 2
Step 2: If Bucket policy fail try step 3
Step 3: If all else fails then nothing works and keep direct link public
```

then that would be fine but for now, ill stick with this solution till further notice.

**Comment by Kinuseka** [comment]
Pretty happy with the results so far, migration script works and I deployed it on my production environment
image

still on bughunting Ill report if I find issues along the way

**Comment by Chocobozzz** [comment]
Closing this PR as we have not found a "perfect" replacement for ACL: https://github.com/Chocobozzz/PeerTube/issues/5497#issuecomment-1464834051

**Pull request closed without merging**
