### PR TITLE
Update left menu and account menu

### PR DESCRIPTION
**Pull request by Chocobozzz**
Updated the left menu:

 * Add *My settings*, *My library*, *Administration* (if admin) below the username
 * Renamed section titles to *In my account*, and *On instance name* for better block scopes identification
 * Removed *Account settings* and *Channel settings* from the user dropdown
 * Add *My notifications in the user dropdown

Splitted the account menu in two:
 * My library containing channels, videos, imports, ownership changes, playlists, subscriptions and history
 * My settings containing account settings, notifications and moderation tools

Others:
 * Moved *My imports* and *Ownership changes* links in the videos page, since it's related to the account videos so we have less entries in the main menu

Discussion:
 * Not sure if we use the orange color for active account links on the left menu:

screen_2020-11-12-16:16:48
screen_2020-11-12-16:16:13

 * Better name for *My settings* of the left menu?

Other screens:
screen_2020-11-12-16:19:47
screen_2020-11-12-16:16:59

### CODE REVIEW

**Comment by kimsible** [comment]
Hi @Chocobozzz, congrat and thanks for all this work !

I love the way the menu entries are displayed now.

Splitting, my-library pages into a my-library page looks clearer, same for « Administration ».

> Better name for My settings of the left menu?

Maybe simply « **My account / Mon compte** » ? I saw that Mobilizon uses that word, maybe we can try ?
I'm not sure if it's consistent with the notifications list and moderation options.

> Not sure if we use the orange color for active account links on the left menu:

The `--mainColorLighter` with  `color: white` on the svg looks bettter (but really not sure) : 
image

Hover could be same as the other menu left items: 
image


Also, I think you can now remove all the `My ...` on H1 titles, buttons and dropdown menus : My channels, My videos, My imports (h1 and button), My playlists, My ownership changes, My subscriptions, My history, My settings (sub menu), My notifications (sub menu), My abuse reports (in dropdown moderation menu).
=> Only My notifications in the user dropdown menu, My settings / account (or something else), My library would stay like that.

**Comment by Chocobozzz** [comment]
> Maybe simply « My account / Mon compte » ? I saw that Mobilizon uses that word, maybe we can try ?

Let's try that

> The --mainColorLighter with color: white on the svg looks bettter (but really not sure) :

:+1:

> Also, I think you can now remove all the My ... on H1 titles, buttons and dropdown menus 

:+1: 

> Video view is not mobile friendly :

Fixed

**Comment by Chocobozzz** [comment]
Account item compromise, with an orange border on the left:

screen_2020-11-13-11:54:14

**Comment by Chocobozzz** [comment]
Merging but feel free to comment. We can still fix/change things

**Comment by kimsible** [comment]
I like the orange border left =) great work, thanks!

**Comment by kimsible** [comment]
Would the label « IN MY LIBRARY » fit better instead of « IN MY ACCOUNT » since My account concerns settings, notifications and moderation ?

image

**Comment by Chocobozzz** [comment]
@kimsible :+1: https://github.com/Chocobozzz/PeerTube/commit/f0048d5edd6394a672c80332e9007413fbba57f5

**Pull request merged**
