### PR TITLE
Add new default different avatar for channel and account

### PR DESCRIPTION
**Pull request by kimsible**
## Description

Add a new default avatar based on Featured icons and for each Actor type : VideoChannel and Account.
This way we can easily see when the default avatar referring to a channel or an account. 

## Related issues

https://github.com/Chocobozzz/PeerTube/issues/3324

## Has this been tested?

- [x] 👍 yes, light tests as follows are enough

Default avatar is only a client side display, so the only tests I made are displaying the changed view as the screenshots show bellow.

## Screenshots

Account menu
avatar1

Comments 
avatar2

Admin tables
avatar3

Account page profile
avatar4

Channel page profile
avatar5

Channel list
avatar6

Video description
avatar7

Search
avatar8

### CODE REVIEW

**Comment by Chocobozzz** [comment]
Hello,

Why removing the old default avatar? I think it's appropriate to define an account, and it's more cheerful than the new avatar.

**Comment by kimsible** [comment]
> Hello,
> 
> Why removing the old default avatar? I think it's appropriate to define an account, and it's more cheerful than the new avatar.

@Chocobozzz sorry if you're attached to it, but it's to be consistent with the rest of the design, the image takes the user / account icon of featured icons.

And sorry again if you did that image, it's not against you, but it's not cheerful for me and some other PeerTube users, it's more creepy and weird to use a big smiley to represent a default profile / account avatar, it's not very common. For example, in QueerMotion, no member understood it was a default avatar at the beginning despite the remark that it's creepy :/.

In any case, I don't say it will fix the fact that a user does not fill its profile and set its avatar but it's really better to be consistent with common design « codes » and the rest of the PeerTube design (features icons).

**Comment by Chocobozzz** [comment]
> @Chocobozzz sorry if you're attached to it, but it's to be consistent with the rest of the design, the image takes the user / account icon of featured icons.

I'm not attached to anything. I just argued that the new one is too austere compared to the current one.

> And sorry again if you did that image, it's not against you

I did not. Please let's leave my *potential* personal feelings out of this discussion :)

> it's more creepy and weird to use a big smiley to represent a default profile

Then we can search for a better alternative. Your edit seems a good idea. I'll see what I can do but it will take time.

**Comment by kimsible** [comment]
> I did not. Please let's leave my potential personal feelings out of this discussion :)

Ok ok =). You put them in the discussion yourself. I understand that a project like PeerTube asks lots of attention and a community (as every community) is not always as cheerful as it should be when it comes to request features or describe an issue, that's why we have to try to not let our personal feelings out too quickly.

> Then we can search for a better alternative. Your edit seems a good idea. I'll see what I can do but it will take time.

Maybe we can ask to a designer ? I'll try to find one interested, we have couple of ones in QueerMotion.

**Pull request merged**
