### PR TITLE
more explicit error messages for file uploads

### LINKED ISSUE #3050: Obvious error message to replace "unknown error"
Hello,

Sometimes, when i upload a video, it fails because of an "unknown error". After some testing, i discovered that it was because of another video was being transcoded, so my CPU was constantly at 100%. So i think the so-called unknown error is hiding the fact that the server doesn't have enough resources for now and that we simply have to wait until transcoding is done, it would be clearer than "unknown error".

### PR DESCRIPTION
**Pull request by rigelk**
## Description

File uploads are often met with network errors. They can also be met with classic HTTP errors as defined in our spec. Both are _dealt with_ (reset + notification), but notification messages only last 5 seconds, and their messages are not always describing the code correctly nor left in the console for later investigation. Since users uploading large files or with unleliable connections are not always monitoring their upload page, they might miss a temporary notification.

This PR brings:
- sticky notification option
- notifications log to the console
- _some_ upload errors now trigger sticky notifications
- RP sets a header showing maximum file size for errors

@Chocobozzz are you interested by the maximum file size information being given by the reverse-proxy, or is it superfluous?

## Related issues

This issue is related to https://github.com/Chocobozzz/PeerTube/issues/324#issuecomment-731694361, and
fixes #3050

## Has this been tested?

- [ ] 👍 yes, I added tests to the test suite
- [ ] 👍 yes, light tests as follows are enough
- [x] 💭 no, because this PR is a draft and still needs work

### CODE REVIEW

**Comment by rigelk** [comment]
@Chocobozzz do you know how I could test that in the CI?

**Comment by Chocobozzz** [comment]
> @Chocobozzz are you interested by the maximum file size information being given by the reverse-proxy, or is it superfluous?

This is a good idea

> do you know how I could test that in the CI?

E2E CI?

**Comment by Chocobozzz** [comment]
What's the status of this PR? I would like to ship it in v3 since upload errors are very frustrating at the moment. But I'm not sure you should use the `sticky` attribute. Instead, I think we should display the error on top of the upload form, with a retry button.

**Comment by rigelk** [comment]
@Chocobozzz I’ll keep the notifier refactoring, as sticky messages might come in handy elsewhere.

**Comment by rigelk** [comment]
I changed the error display so that it both notifies and keep the message in the progressbar, which now has a retry and cancel button. Maybe some errors could disable the retry button (like error 413 which a retry will not help solve).

**Comment by Chocobozzz** [comment]
Nice!

**Pull request merged**
