### PR TITLE
added installer command to package.json scripts; yarn run installer

### PR DESCRIPTION
**Pull request by FlatEarthTruther**
#1171

### CODE REVIEW

**Comment by Chocobozzz** [comment]
I would prefer to keep the `yarn install...`, it's better for people to know what they're doing (in particular, using the `yarn` tool). The `rm` part has to be done on broken installations (because someone made the wrong command etc). Moreover, it does not cover the production case.

**Comment by FlatEarthTruther** [comment]
It's just nicer to type less than to have to type more always, maybe we can have a dev-installer, prod-installer script instead if it doesn't cover the production use case, because for me even though I know what it does I don't always want to type it all the time and after going away for a month or two from the project I like to pop into the package json to see all the administration/development commands and go from there, so mostly I add all commands to the scripts for reference and to make things easier to remember after a while. I may go on vacation and come back to having to look through many docs to just find this command, whereas I could just find it in the package.json file instead. It anything we can multiple one for prod and one for dev, still it uses the install command originally but this just adds those hard to remember params in a single go.

**Comment by FlatEarthTruther** [comment]
It's not like it's overwriting the install command, it just extends it. people can still use the yarn install all day long if they want, and part of the automation process who cares if it removes the node_modules and reinstalls them if broken install or not.

**Comment by FlatEarthTruther** [comment]
This would've been a duplication of `yarn run danger:clean:modules` && `yarn install --pure-lockfile` so no worries, I guess after I spend more time on this project I'll get to know it more.

**Pull request closed without merging**
