### PR TITLE
peertube-import-videos using arbitrary additional metadata

### LINKED ISSUE #2385: Want to add to youtube-dl extractor to enable better 'Import with URL' results
**What happened?**
I imported a video from a youtube-dl-recognized PeerTube instance (peertube.co.uk) and there were some missing or unexpected results:

- Description is truncated
- Language missing (see https://github.com/Chocobozzz/PeerTube/issues/2252)
- License missing (see https://github.com/Chocobozzz/PeerTube/issues/2252)
- Captions are missing (see https://github.com/Chocobozzz/PeerTube/issues/1016)
- Original publish date is overwritten
(Support was untested, I don't know what that is for :/ )

**What do you expect to happen instead?**
I expect these to be properly extracted by youtube-dl and imported by PeerTube.

### I intend to help fix this by improving the youtube-dl extractor.
It already extracts the license properly. I can probably add fields to extract the language and (if we determine it to be expected behaviour) the original publish date if it exists. I am unsure about the captions but I believe that is possible. I will need feedback on the support section.

After this, is should be simple enough for someone to fix the PeerTube import script.

### LINKED ISSUE #2467: Ability to store the original video URL a meta for imports
**What happened?**

When importing a video, this line tests for title equality.
https://github.com/Chocobozzz/PeerTube/blob/a15871560f80e07386c1dabb8370cd2664ecfd1f/server/tools/peertube-import-videos.ts#L140

This is suboptimal
1. Because title can change at the source of the destination, resulting in duplicates.
2. Because Peertube imported video does not hold the original location/unique id of the source which may be useful (for establishing a mapping for example)

**What do you expect to happen instead?**
The importer could fill-in a meta like "Original URL" or "Original ID" containing the Youtube/Vimeo/... URL/ID.

**Additional information**
* PeerTube version or URL: 2.0.0

### PR DESCRIPTION
**Pull request by drzraf**
- Fixes #2467
- Probably fixes #2385
- Offers a workaround for #2348 (and #2006 ?)

Bundles #2473

### CODE REVIEW

**Comment by Chocobozzz** [comment]
Thanks for the PR but why don't you use the commander parameter instead? For example: `--video-name '@video.name`

Also, I'm not sure to understand how this fix https://github.com/Chocobozzz/PeerTube/issues/2467 since you don't add another column in the database

**Comment by drzraf** [comment]
> Thanks for the PR but why don't you use the commander parameters instead? For example: `--video-name '@video.name`

Because it didn't sound flexible enough for *any* metadata. We would have to specify any possible existing or future metadata as an allowed option on the command-line syntax.

> Also, I'm not sure to understand how this fixes #2467 since you don't add another column in the database.

That's the point I misunderstood and didn't checked it.
I wrongly believed that any arbitrary metadata would be stored in a kind of "opaque" metadata fieldset.
I didn't thought each and every metadata should be a defined field by itself, allowed by the app' beforehand.

(I find that situation rather cumbersome. Isn't possible to provide an opaque `array` fieldset for arbitrary, user-provided, metadata? Could namespaced them under `@user.` if really needed ? Or maybe hijacking/extending tags for this ? :))

**Comment by Chocobozzz** [comment]
> (I find that situation rather cumbersome. Isn't possible to provide an opaque array fieldset for arbitrary, user-provided, metadata? Could namespaced them under @user. if really needed ? Or maybe hijacking/extending tags for this ? :))

You could try to use a plugin to store additional video metadata I think. But we don't really want to store non-known additional metadata for now for different reasons (we use a relational DB, AP schema etc).

**Comment by drzraf** [comment]
I understand your concern, but I'm pretty sure there is an agnostic (and controlled) way to provide such extensibility:

- An `extra`/`user` object which contains two keys: `public` and `private`, whose serialization would be limited, to say, 64 kB and stored in a newly created, dedicated [Sequelize.JSONB](https://sequelize.org/master/class/lib/data-types.js~JSONB.html) column.

- During storage, the `{private: {opaque object}, public: {opaque object}}` keys are stored as-is (implicitly serialized/ordered/deduplicated using JSONB)
- During `/video/` API calls, data is retrieved (implicitly `JSON.parse`'d) and provided as-is. (Using `private/public` according to API call permissions). Data would be available in the API response via something like `metadata.extra.public/private`.

Don't you think it'd would be a safe enough and non-intrusive way to provide the needed extensibility and resolve problems like "`storing extra-meta during import`". It'd would also be a way for plugins to extend the data-model (naive and limited but better than nothing).

Eg: `metadata.user.private.@myplugin.anything = whatever`
According to [Sequalize](https://github.com/sequelize/sequelize/issues/4963) [stackoverflow](https://stackoverflow.com/questions/49613110) and [blog posts](https://www.compose.com/articles/is-postgresql-your-next-json-database), PostgreSQL even provide a way to query/search/filter based on these nested JSON data attributes (!)

Wouldn't this sound better than messing-up with [Sequelize hooks](https://sequelize.org/v5/manual/hooks.html) to play with database schema (and upgrade/downgrade scripts) that would be way more complex to developers.

**Comment by Chocobozzz** [comment]
We designed a plugin system where you can store data you want, and so create a hashmap with `{ [ videoId: number ]: metadata: any }`. It misses dedicated API route so the client get this data but we'll try to implement this in the future.

Or you could use https://github.com/Chocobozzz/PeerTube/pull/2411 and add you metadata in the public `metadata` field create by @rigelk.

**Comment by Chocobozzz** [comment]
Closing due to inactivity. Feel free to comment!

**Pull request closed without merging**
