### PR TITLE
Private instance mode

### PR DESCRIPTION
**Pull request by Bricklou**
This PR is a solution for #520 which instance owner to make their instance private. But I think it is missing some static file and route blocking (for example videos or preview blocking when user is not logged in)

If private mode is enabled, my changes;
- Force the user to be logged in to access to videos
- Disable follow system
- Allow admin to update the mode from the configuration page

### CODE REVIEW

**Comment by Chocobozzz** [comment]
What's the advantage of merging this PR compared to the new internal privacy setting?

**Comment by Bricklou** [comment]
This merging lock all access by default, so users can put their videos in public and only logged user can access to them. If user is not logged in, all routes redirect to the login page. It is equivalent to the new system but it is for all the instance by default and can't be bypassed by users.

**Comment by Chocobozzz** [comment]
> so users can put their videos in public and only logged user can access to them.

It's an inconsistent behaviour then. 

I don't think this is the right way to do it. It's a little bit complex and error prone: we need to add middlewares for many routes (in the client **and** in the server). We'll possibly forgot one resulting in a security issue. IMHO locking the privacy modes for your current instance is a cleaner and safer way to achieve the same goal.

**Comment by Bricklou** [comment]
It's just a try, if it is necessary to rework all the system to avoid security problems, I can. But globally, the idea is there: ensure that access is restricted to guest persons on an Peertube instances.

And when I say that user can publish public video, I meant available for every logged in peoples.

**Comment by rigelk** [comment]
@Bricklou as mentioned before, the current implementation changes confidentiality definitions, is hard to maintain in the long term and error-prone doing so. Since we integrated a new confidentiality mode for videos restricting access to logged-in users, the issue is less pressing.

Please open a new issue to properly discuss your envisioned functionality.

**Comment by derMart** [comment]
@rigelk This confidentiality mode is really nice news. Having trouble to find this in the documentation, could you link me there?

**Comment by ManuelBarrioLinares** [comment]
So... What is the best current way to achieve this level of privacy for an organization?

**Pull request closed without merging**
