### PR TITLE
[ImgBot] optimizes images

### PR DESCRIPTION
**Pull request by Jorropo**
Made from issue #822 

```
*Total -- 289.13kb -> 211.82kb (26.74%)

/support/doc/development/server/upload-video.png -- 56.19kb -> 33.83kb (39.8%)
/support/doc/development/client/components-tree.png -- 31.81kb -> 19.82kb (37.68%)
/client/src/assets/images/icons/icon-512x512.png -- 14.24kb -> 9.97kb (30.03%)
/server/tests/fixtures/avatar-resized.png -- 1.69kb -> 1.19kb (29.24%)
/server/tests/fixtures/avatar2-resized.png -- 1.68kb -> 1.21kb (28.41%)
/client/src/assets/images/default-avatar.png -- 1.63kb -> 1.24kb (23.89%)
/server/tests/fixtures/avatar.png -- 1.63kb -> 1.24kb (23.89%)
/server/tests/fixtures/avatar-big.png -- 143.15kb -> 111.56kb (22.06%)
/client/src/assets/images/icons/icon-192x192.png -- 3.58kb -> 2.86kb (20.21%)
/server/tests/fixtures/video_short1.webm.jpg -- 2.83kb -> 2.36kb (16.75%)
/client/src/assets/images/icons/icon-144x144.png -- 2.34kb -> 1.95kb (16.53%)
/client/src/assets/images/icons/icon-96x96.png -- 1.91kb -> 1.62kb (15.16%)
/server/tests/fixtures/video_short.ogv.jpg -- 2.56kb -> 2.18kb (14.71%)
/server/tests/fixtures/video_short.mp4.jpg -- 2.56kb -> 2.19kb (14.51%)
/server/tests/fixtures/video_short.webm.jpg -- 2.55kb -> 2.19kb (14.38%)
/server/tests/fixtures/video_short1-preview.webm.jpg -- 9.94kb -> 8.52kb (14.31%)
/server/tests/fixtures/video_short3.webm.jpg -- 2.82kb -> 2.46kb (12.65%)
/server/tests/fixtures/video_short2.webm.jpg -- 3.11kb -> 2.74kb (11.93%)
/client/src/assets/images/icons/icon-72x72.png -- 1.72kb -> 1.53kb (11.1%)
/client/src/assets/images/icons/icon-48x48.png -- 1.18kb -> 1.17kb (1%)
```

### CODE REVIEW

**Comment by rigelk** [comment]
We should exclude fixtures as changing them can impact the tests.

**Comment by Glandos** [comment]
I don't know how ImgBot works, but you can use [MozJPEG jpegtran](https://github.com/mozilla/mozjpeg) and [zopflipng](https://github.com/google/zopfli/). Both tools currently give the best results for respectively JPEG and PNG lossless recompression.

**Comment by Jorropo** [comment]
Img bot propose some pr daily and make an loss less compression

**Comment by Chocobozzz** [comment]
@Jorropo Please checkout your modifications on test images

**Comment by Jorropo** [comment]
@Chocobozzz made

**Comment by Chocobozzz** [comment]
Thanks @Jorropo!

**Pull request merged**
