### PR TITLE
Display username in password-reset mail

### LINKED ISSUE #2954: Wrong username account displayed in reset-password mail
The password reset procedure send an email with the link to reset it, but in the mail text the username account is not displayed, the variable seems to be escaped :

Peertube-issue-account-reset-password

### PR DESCRIPTION
**Pull request by kimsible**
fixes #2954

### CODE REVIEW

**Comment by kimsible** [comment]
@rigelk I think it is a fix for an important issue because when the user receives the notification email, when can it be know the notification concerns the user's account ? For us, as developer, it's pretty obvious yes but for the user it could be blocking.

**Comment by rigelk** [comment]
Yes - I'm just renaming because prefixing with "fix :" is not describing the content of the PR.

**Comment by kimsible** [comment]
!

> Yes - I'm just renaming because prefixing with "fix :" is not describing the content of the PR.

Ok, it has nothing to do with the PR but is there a label to tag fixes ?

**Comment by rigelk** [comment]
For PRs, the determinant of its nature is the issue it solves, so using the `fixes #..` syntax in the end of the description or as a "stamp" in a commit message helps determine that.

**Comment by kimsible** [comment]
> For PRs, the determinant of its nature is the issue it solves, so using the `fixes #..` syntax in the end of the description or as a "stamp" in a commit message helps determine that.
> 
> We use other labels to help us triage PRs (maintenance/priority), but not determine their fix/plain enhancement status.

Thanks !

**Comment by kimsible** [comment]
> replace the bland `Hi,` with `Hi {username},`. It would solve the current problem and more to come.

`Hi {username}` is already used in `/server/lib/emails/common/greeting.pug`

https://github.com/Chocobozzz/PeerTube/blob/develop/server/lib/emails/common/greetings.pug#L5

```
  if username
    p Hi #{username},
  else
    p Hi,
```

**Comment by rigelk** [comment]
Yes, I just meant to send inject the variable in other email templates

**Comment by Chocobozzz** [comment]
Please use `release/2.3.0` as base branch since it's a fix, so we can fix this issue in the next release

**Pull request merged**
