### PR TITLE
Add PEERTUBE_INSTANCE_CUSTOM_CSS and PEERTUBE_INSTANCE_CUSTOM_JS

### PR DESCRIPTION
**Pull request by fflorent**
This allow a user with custom CSS and JS to persist it accross container removal.

What do you think?
Florent

### CODE REVIEW

**Comment by Chocobozzz** [comment]
I think we should put the configuration files in `/data/config` directory (`data` is a volume).

Ping @Angristan @bnjbvr

**Comment by Angristan** [comment]
I have two volumes now:

```
    volumes:
      - ./data:/data
      - ./config/local-production.json:/app/support/docker/production/config/local-production.json
```

But yes that would be a good idea

**Comment by fflorent** [comment]
Right, so `support/docker/production/config/*` should be moved where ? Or could we just bind `support/docker/production/config` to `./config` maybe (with an overlayed volume, not sure whether that's feasible or relevant)?

**Comment by Chocobozzz** [comment]
I implemented it :) https://github.com/Chocobozzz/PeerTube/commit/fd5e57bbe2accbdb16b6aa65337c5ef44b5bd8fb

**Comment by Angristan** [comment]
If I'm not mistaken, the CMD will run as the last USER, so now it's root 🤔

**Comment by Chocobozzz** [comment]
@Angristan I'm sorry I don't understand. The `USER root` was just moved, so it should not change the previous behaviour.

**Comment by Angristan** [comment]
Nevermind, I didn't see all the `gosu` stuff

**Comment by bnjbvr** [comment]
(Just wanted to say good job!)

**Comment by Angristan** [comment]
So what should I with my volumes now? I'm lost :(

**Comment by Chocobozzz** [comment]
@Angristan Save your local configuration `local-production.json`, then declare `./config:/config` in volumes, then `docker-compose up` and finally copy your `local-production.json` inside the config folder.

**Comment by Angristan** [comment]
Thanks!

I have this issue:

```
[undefined:443] 2018-05-09 22:17:44.063 info: Getting client tokens for host peertube.angristan.xyz is forbidden (expected undefined).
```

screenshot_10-05-2018_00-18-55

Could it be related?

**Comment by fflorent** [comment]
@Angristan Have you renamed the `PEERTUBE_HOSTNAME` variable into `PEERTUBE_WEBSERVER_HOSTNAME` in the docker-compose.yml and/or in the `docker-compose up` command you invoke?

**Comment by Angristan** [comment]
Indeed, thanks a lot @fflorent!

**Pull request closed without merging**
