### PR TITLE
support/systemd: add more sandboxing options

### PR DESCRIPTION
**Pull request by Izorkin**
## Description
Added more sandboxing options.
This options tested on my peerube instance. I did not find any errors in the work.
Not changed this options:
```
PrivateDevices=false
PrivateTmp=false
```

### CODE REVIEW

**Comment by LecygneNoir** [comment]
Hello!

I am trying to test the unit from start to end on a fresh install following the actual doc line by line, but I get an error when starting peertube and it tries to check its directory:

```
mai 14 14:06:37 saagie.home peertube[223413]: [example.com:80] 2021-05-14 14:06:37.636 error: Cannot install application. {
mai 14 14:06:37 saagie.home peertube[223413]:   "err": {
mai 14 14:06:37 saagie.home peertube[223413]:     "stack": "Error: EROFS: read-only file system, rmdir '/var/www/peertube/storage/cache/previews'",
mai 14 14:06:37 saagie.home peertube[223413]:     "message": "EROFS: read-only file system, rmdir '/var/www/peertube/storage/cache/previews'",
mai 14 14:06:37 peertube[223413]:     "errno": -30,
mai 14 14:06:37 peertube[223413]:     "code": "EROFS",
mai 14 14:06:37 peertube[223413]:     "syscall": "rmdir",
mai 14 14:06:37 peertube[223413]:     "path": "/var/www/peertube/storage/cache/previews"
mai 14 14:06:37 peertube[223413]:   }
mai 14 14:06:37 peertube[223413]: }
```

All directory are owned by peertube user and writable by him.

I am not a systemd master sorry, so I am unable to find exactly where is the glitch (I suspect a problem between PrivateMount and WorkingDirectory thought).

Could you confirm you have done no specific modification on your system to make it works?

Thanks!

**Comment by Izorkin** [comment]
By default allowed writing only this directories - `/var/lib/peertube`
Need add this option:
```
ReadWritePaths = /var/www/peertube
```

**Comment by Chocobozzz** [comment]
Hello,

Thanks for the PR but I rather not add other security directives to systemd. The enabled ones have already given me headaches and taken up a lot of my time in support

**Comment by Izorkin** [comment]
Fixed PR.

**Pull request closed without merging**
