### PR TITLE
Account identifier text description

### PR DESCRIPTION
**Pull request by DontUseGithub**
>  The username is a unique identifier of your account on this and all the other instances.

this is true if we consider "john@domain.com" as "an account". If by "an account" you only mean "john" then the text needs to be changed to something like:

> The username is a unique identifier of your account on this instances. Together with the domain name - it becomes unique across all instances.

In any case, English native speakers I'm open to suggestions on how to improve this :)

### CODE REVIEW

**Comment by Aluriak** [comment]
Good improvement, crystal clear explanation. Why a dash instead of a comma ?

**Comment by DontUseGithub** [comment]
@Aluriak Thank you. Right, the dash feels unnecessary, I'll remove it. 

Have you checked both commits, do you think they both look good?

- https://github.com/Chocobozzz/PeerTube/pull/2447/commits/bf94eb0e0527eb5467c942b75b4eab9036b206d1
- https://github.com/Chocobozzz/PeerTube/pull/2446/commits/09c982dbefac401b9c62c5229f4dc69788834e07

**Comment by rigelk** [comment]
@DontUseGithub next time please do it in one PR, as they are closely related.

**Comment by Aluriak** [comment]
> Have you checked both commits, do you think they both look good?

yes, i should have make the same remark there !

**Pull request merged**
