### PR TITLE
HLS experimental support

### PR DESCRIPTION
**Pull request by Chocobozzz**
https://github.com/Chocobozzz/PeerTube/issues/1237#issuecomment-457220443

### CODE REVIEW

**Comment by mrlika** [comment]
Why do you use videojs? Is it used all over PeerTube?

P2P Media Loader support is not perfect in case of videojs because it does not use its build in [HTTP streaming](https://github.com/videojs/http-streaming) plugin but relies on a custom plugin that provides hlsjs engine support in the player. And the plugin is not actively developed.

**Comment by mrlika** [comment]
Ok. I will try to add videojs HTTP streaming support for P2P Media Loader in nearest future.

**Comment by rigelk** [comment]
@mrlika :astonished: that would be more than welcome ! Thanks

**Comment by tcitworld** [comment]
:tada:

**Comment by Chocobozzz** [comment]
Demo: https://peertube2.cpy.re/videos/watch/4b997fc0-e106-42d9-bff9-ae9d64902bbb?mode=p2p-media-loader

**Pull request merged**
